// next/components/Forms/Role/UpdateRoleResources.tsx
import React from 'react';
import { Typography } from '@mui/material';

import lang from '../../../lib/lang';
import rolesApi from '../../../store/api/rolesApi';
import { makeErrorText } from '../../../lib/functions';
import { IResource, IRole, IRolesResources } from '../../../lib/types';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { addAlert } from '../../../store/slices/appSlice';
import FormActions from '../FormActions';
import FormBoxStyled from '../FormBoxStyled';
import ResourceRights from '../Resource/ResourceRights';
import { ROUTES } from '../../../lib/constants';
import useRights from '../../../hooks/useRights';

const UpdateRoleResources: React.FC<{
  role: IRole;
  resources: IResource[];
}> = ({ role, resources }) => {
  const dispatch = useAppDispatch();
  const userLang = useAppSelector(store => store.app.userLang);
  const [update, updateReq] = rolesApi.useUpdateResourcesMutation();
  const [updatedRights, setUpdatedRights] = React.useState(
    role.resources?.map(value => value.RolesResources) || []
  );
  const rights = useRights(ROUTES.api.roles);

  const updateHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    update({
      id: role.id,
      fields: updatedRights,
    });
  };

  const updateRights = (newRights: IRolesResources) => {
    const filtered = updatedRights.filter(value => {
      if (
        newRights.roleId == value?.roleId &&
        newRights.resourceId == value?.resourceId
      ) {
        return false;
      } else {
        return true;
      }
    });
    if (!(
      newRights.creating == false &&
      newRights.reading == false &&
      newRights.updating == false &&
      newRights.deleting == false
    )) {
      filtered.push(newRights);
    }
    setUpdatedRights(filtered);
  };

  React.useEffect(() => {
    if (updateReq.isLoading) {
      return;
    }
    if (updateReq.data === false || updateReq.error) {
      dispatch(addAlert({ type: 'error', text: makeErrorText(updateReq.error, userLang) }));
    }
    if (updateReq.data) {
      dispatch(addAlert({ type: 'success', text: lang.get(userLang)?.success }));
    }
  }, [
    updateReq.data, updateReq.error, updateReq.isLoading,
    dispatch, userLang,
  ]);

  return (
    <FormBoxStyled onSubmit={updateHandler}>
      <Typography
        component="h2"
        variant="h5"
        sx={{ my: 1.5, lineHeight: 1 }}
      >
        {lang.get(userLang)?.resources}
      </Typography>
      {resources.map(resource => (
        <ResourceRights
          key={`ResourceRights.${resource.id}`}
          roleId={role.id}
          resource={resource}
          rights={updatedRights.filter(value => value?.resourceId == resource.id)[0]}
          setRights={updateRights}
        />
      ))}
      {resources && (
        <FormActions
          update={{
            loading: updateReq.isLoading,
            disabled: !rights.updating,
          }}
        />
      )}
    </FormBoxStyled>
  );
};
export default UpdateRoleResources;

// nuxt/components/Forms/Role/UpdateRoleResources.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import ResourceRights from '../Resource/ResourceRights.vue'
import FormButton from '../FormButton.vue'
import { useRolesStore } from '~/stores/roles'
import { useMainStore } from '~/stores/main'
import type { IResource, IRole, IRolesResources } from '~/utils/types'

const { role, resources } = defineProps<{ role: IRole; resources: IResource[] }>()

const updatedRights = ref<IRolesResources[]>(resources.map((resource) => {
  if (role.resources) {
    for (const roleResource of role.resources) {
      if (roleResource.id === resource.id && roleResource.RolesResources)
        return roleResource.RolesResources
    }
  }
  return {
    roleId: role.id,
    resourceId: resource.id,
    creating: false,
    reading: false,
    updating: false,
    deleting: false,
  }
}))

const { t } = useI18n()
const rolesStore = useRolesStore()
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.roles)

function submitHandler() {
  rolesStore.updateResources({
    id: role.id,
    fields: updatedRights.value,
  })
}

function setRights(rights: IRolesResources) {
  updatedRights.value = updatedRights.value.map((value) => {
    if (value.resourceId === rights.resourceId)
      return rights
    return value
  })
}

watch(
  () => rolesStore.updateResourcesPending,
  () => {
    if (rolesStore.updateResourcesPending === true)
      return
    if (rolesStore.updateResourcesError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(rolesStore.updateResourcesError) })
    if (rolesStore.updateResourcesData)
      mainStore.addAlert({ type: 'success', text: t('success') })
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <div class="d-flex flex-row">
      <ResourceRights
        v-for="resource of resources"
        :key="`resourceRights.${resource.id}`"
        :role-id="role.id"
        :resource="resource"
        :rights="updatedRights.filter(value => value.resourceId === resource.id)[0]"
        @update="setRights"
      />
    </div>
    <FormButton
      type="submit" color="success" prepand-icon="mdi-content-save"
      :loading="rolesStore.updateResourcesPending" :disabled="!rights.updating"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBox>
</template>
