// apps/frontend/panel-vue/components/features/users/UserCreate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const emit = defineEmits<{
  create: [value: IUser]
}>()

const { t, locale } = useI18n()
const newData = ref<TUserCreate>({
  email: '',
  password: '',
  name: '',
})
const { data, error, execute, status } = usersApi.create(newData)
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.users)

watch(data, () => {
  if (data.value) {
    mainStore.addAlert({ type: 'success', text: t('success') })
    emit('create', data.value)
  }
})

watch(error, () => {
  if (error.value) {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
  }
})
</script>

<template>
  <UserForm
    create-show
    :create-disabled="!rights.creating"
    :create-loading="status === 'pending' || Boolean(data)"
    @create="(fields) => {
      newData = fields
      execute()
    }"
  />
</template>

// apps/frontend/panel-react/src/features/users/UserCreate.tsx
import { FC, useEffect } from "react";

import useRights from "@/shared/hooks/useRights";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import { getErrorText, ROUTES } from "@ap/shared/dist/libs";
import UserForm from "@/entities/user/UserForm";
import { IUser } from "@ap/shared/dist/types";
import usersApi from "@/entities/user/api";

const UserCreate: FC<{ onCreate?: (data: IUser) => void }> = ({ onCreate }) => {
  const dispatch = useAppDispatch();
  const tRef = useTranslateRef();
  const lRef = useLanguageRef();
  const [create, createReq] = usersApi.useCreateMutation();
  const rights = useRights(ROUTES.api.users);

  useEffect(() => {
    if (createReq.data) {
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
      onCreate?.(createReq.data);
    }
  }, [createReq.data, dispatch, onCreate, tRef]);

  useEffect(() => {
    if (createReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(createReq.error, lRef.current),
        })
      );
    }
  }, [createReq.error, dispatch, lRef]);

  return (
    <UserForm
      onCreate={(fields) => create(fields)}
      createDisabled={!rights.creating}
      createLoading={createReq.isLoading || Boolean(createReq.data)}
    />
  );
};
export default UserCreate;
