// apps/frontend/panel-vue/components/features/users/UserRolesUpdate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const { user } = defineProps<{
  user: IUser
  roles: IRole[]
}>()

const updatedRoles = ref<IUsersRoles[]>(
  user.roles?.map(role => ({ roleId: role.id, userId: user.id })) ?? [],
)
const { t, locale } = useI18n()
const { status, error, execute } = usersApi.updateRoles({
  id: user.id,
  fields: { items: updatedRoles },
})
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.users)

watch(error, () => {
  if (!error.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <UserRolesForm
    :user="user"
    :roles="roles"
    :disabled="!rights.updating"
    :loading="status === 'pending'"
    @update="(newUserRoles) => {
      updatedRoles = newUserRoles
      execute()
    }"
  />
</template>

// apps/frontend/panel-react/src/features/users/UserRolesUpdate.tsx
import { FC, useEffect } from "react";

import useRights from "@/shared/hooks/useRights";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import { IRole, IUser } from "@ap/shared/dist/types";
import { getErrorText, ROUTES } from "@ap/shared/dist/libs";
import UserRolesForm from "@/entities/user/UserRolesForm";
import usersApi from "@/entities/user/api";

const UserRolesUpdate: FC<{
  user: IUser;
  roles: IRole[];
}> = ({ user, roles }) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const [update, updateReq] = usersApi.useUpdateRolesMutation();
  const rights = useRights(ROUTES.api.users);

  useEffect(() => {
    if (updateReq.isSuccess) {
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
    }
  }, [updateReq.isSuccess, dispatch, tRef]);

  useEffect(() => {
    if (updateReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(updateReq.error, lRef.current),
        })
      );
    }
  }, [updateReq.error, dispatch, lRef]);

  return (
    <UserRolesForm
      user={user}
      roles={roles}
      onUpdate={(newUserRoles) =>
        update({
          id: user.id,
          fields: { items: newUserRoles },
        })
      }
      updateDisabled={!rights.updating}
      updateLoading={updateReq.isLoading}
    />
  );
};
export default UserRolesUpdate;
