// next/src/entities/Forms/Panel/Roles/UpdateRoleResourcesForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import SaveIcon from '@mui/icons-material/Save';

import Form from '@/shared/kit/Form/Form';
import FormButton from '@/shared/kit/Form/FormButton';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import useRights from '@/shared/hooks/useRights';
import ResourceRightsFields from '../Resources/ResourceRightsFields';
import { IRoleAndResources } from '@/shared/api/roles/types';
import { useAppDispatch } from '@/shared/store/hooks';
import rolesApi from '@/shared/api/roles/rolesApi';
import { IRolesResources } from '@/shared/api/resources/types';
import { addAlert } from '@/shared/store/slices/appSlice';
import { makeErrorText } from '@/shared/lib/utils';

const UpdateRoleResourcesForm: FC<IRoleAndResources> = ({
  role,
  resources,
}) => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const t = useT();
  const [update, updateReq] = rolesApi.useUpdateResourcesMutation();
  const [updatedRights, setUpdatedRights] = useState(
    role.resources?.map((value) => value.RolesResources) || []
  );
  const rights = useRights(ROUTES.api.roles);

  const formHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    update({
      id: role.id,
      fields: updatedRights,
    });
  };

  const updateRights = (newRights: IRolesResources) => {
    const filtered = updatedRights.filter((value) => {
      if (
        newRights.roleId == value?.roleId &&
        newRights.resourceId == value?.resourceId
      ) {
        return false;
      } else {
        return true;
      }
    });
    if (
      !(
        newRights.creating == false &&
        newRights.reading == false &&
        newRights.updating == false &&
        newRights.deleting == false
      )
    ) {
      filtered.push(newRights);
    }
    setUpdatedRights(filtered);
  };

  useEffect(() => {
    if (updateReq.data) {
      dispatch(addAlert({ type: 'success', text: d[lang.current].success }));
    }
  }, [updateReq.data, dispatch, lang]);

  useEffect(() => {
    if (updateReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(updateReq.error, lang.current),
        })
      );
    }
  }, [updateReq.error, dispatch, lang]);

  return (
    <Form onSubmit={formHandler}>
      {resources?.map((resource) => (
        <ResourceRightsFields
          key={`ResourceRights.${resource.id}`}
          roleId={role.id}
          resource={resource}
          rights={
            updatedRights.filter((value) => value?.resourceId == resource.id)[0]
          }
          setRights={updateRights}
        />
      ))}
      <br />
      {!resources || (resources.length === 0 && t.error)}
      <FormButton
        type="submit"
        color="success"
        startIcon={<SaveIcon />}
        disabled={
          !rights.updating ||
          updateReq.isLoading ||
          !resources ||
          resources.length === 0
        }
      >
        {t.update}
      </FormButton>
    </Form>
  );
};
export default UpdateRoleResourcesForm;

// nuxt/components/entities/Forms/Role/UpdateRoleResourcesForm.vue
<script setup lang="ts">
import type { IResource, IRolesResources } from '~/api/resources/types'
import rolesApi from '~/api/roles/rolesApi'
import type { IRole } from '~/api/roles/types'
import ResourceRightsFields from '~/components/entities/Forms/Resource/ResourceRightsFields.vue'
import Form from '~/components/shared/kit/Form/Form.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import { useMainStore } from '~/store/main/main'

const { role, resources } = defineProps<{ role: IRole, resources: IResource[] }>()

const updatedRights = ref<IRolesResources[]>(resources.map((resource) => {
  if (role.resources) {
    for (const roleResource of role.resources) {
      if (roleResource.id === resource.id && roleResource.RolesResources)
        return roleResource.RolesResources
    }
  }

  return {
    roleId: role.id,
    resourceId: resource.id,
    creating: false,
    reading: false,
    updating: false,
    deleting: false,
  }
}))

const { t, locale } = useI18n()
const { data, error, execute, pending } = rolesApi.updateResources()
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.roles)

function submitHandler() {
  execute({
    id: role.id,
    fields: updatedRights.value,
  })
}

function setRights(rights: IRolesResources) {
  updatedRights.value = updatedRights.value.map((value) => {
    if (value.resourceId === rights.resourceId)
      return rights

    return value
  })
}

watch(
  pending,
  () => {
    if (pending.value) return

    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })

    if (data.value)
      mainStore.addAlert({ type: 'success', text: t('success') })
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <div class="d-flex flex-row">
      <ResourceRightsFields
v-for="resource of resources" :key="`resourceRights.${resource.id}`" :resource="resource"
        :rights="updatedRights.filter(value => value.resourceId === resource.id)[0]" :role-id="role.id"
        @update="setRights" />
    </div>
    <FormButton
color="success" :disabled="!rights.updating" :loading="pending" prepand-icon="mdi-content-save"
      type="submit">
      {{ $t('update') }}
    </FormButton>
  </Form>
</template>
