// apps/frontend/panel-vue/components/features/Auth/SignUpSuccessForm.vue
<script setup lang="ts">
defineEmits<{
  close: []
}>()
</script>

<template>
  <FormBase @submit="$emit('close')">
    <FormAlert
      :text="$t('registrationSuccessText')"
      type="success"
    />
    <FormButton
      block
      color="info"
      type="submit"
    >
      {{ $t('signIn') }}
    </FormButton>
  </FormBase>
</template>

// next/src/features/Auth/SignUpSuccessForm.tsx
import { FC } from 'react';

import FormBase from '@/shared/ui/Form/FormBase';
import FormButton from '@/shared/ui/Form/FormButton';
import useTranslate from '@/shared/hooks/useTranslate';
import FormAlert from '@/shared/ui/Form/FormAlert';

const SignUpSuccessForm: FC<{
  onClose?: () => void;
}> = ({ onClose }) => {
  const t = useTranslate();

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onClose?.();
  };

  return (
    <FormBase onSubmit={submitHandler}>
      <FormAlert severity="success">{t.registrationSuccessText}</FormAlert>
      <FormButton type="submit" fullWidth>
        {t.signIn}
      </FormButton>
    </FormBase>
  );
};
export default SignUpSuccessForm;
