// nuxt/components/features/Auth/SignInGoogleForm.vue
<script setup lang="ts">
import Form from '~/components/shared/ui/Form/Form.vue'
import authApi from '~/api/auth/authApi'
import FormAlert from '~/components/shared/ui/Form/FormAlert.vue'

const { t, locale } = useI18n()
const errorText = ref<string | null>(null)
const hash = new URLSearchParams(location?.hash.slice(1) || '')
const { data, error, execute } = authApi.signInGoogle()

watch(error, () => {
  if (error.value)
    switch (error.value?.status) {
      case 410:
        errorText.value = t('userDeleted')
        break
      default:
        errorText.value = getErrorText(error.value, locale.value)
    }
})
structuredClone
onMounted(() => {
  if (hash.has('access_token')) {
    execute({ googleAccessToken: hash.get('access_token')! })
  } else {
    errorText.value = t('error')
  }

  const messageHandler = (event: MessageEvent<string>) => {
    if (!data.value) return
    if (event.data === hash.get('state')) {
      const result: IWindowMessage<IUser> = {
        type: ROUTES.ui.signInGoogle,
        payload: toRaw(data.value),
      }
      event.source?.postMessage(result)
      window.removeEventListener('message', messageHandler)
    }
    window.close()
  }

  window.addEventListener('message', messageHandler)
})
</script>

<template>
  <Form>
    <FormAlert v-if="errorText" :text="errorText" type="error" />
    <v-card-text v-else class="text-center py-3">
      {{ $t('loading') }}...
    </v-card-text>
  </Form>
</template>

// next/src/features/Auth/SignInGoogleForm.tsx
import { FC, useEffect, useRef, useState } from 'react';
import { Typography } from '@mui/material';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import Form from '@/shared/ui/Form/Form';
import FormAlert from '@/shared/ui/Form/FormAlert';
import authApi from '@/shared/api/auth/authApi';
import { getErrorText, IUser, IWindowMessage, ROUTES } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const SignInGoogleForm: FC = () => {
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const hash = useRef(
    new URLSearchParams(
      typeof location === 'object' ? location.hash.slice(1) : ''
    )
  );
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signInGoogle, { data, error }] = authApi.useLazySignInGoogleQuery();

  useEffect(() => {
    if (hash.current.has('access_token')) {
      signInGoogle({ googleAccessToken: hash.current.get('access_token')! });
    } else {
      setErrorText(tRef.current.error);
    }
  }, [signInGoogle, tRef]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 410:
          setErrorText(tRef.current.userDeleted);
          break;
        default:
          setErrorText(getErrorText(error, lRef.current));
          break;
      }
    }
  }, [error, tRef, lRef]);

  useEffect(() => {
    if (!data) return;

    const messageHandler = (event: MessageEvent<string>) => {
      if (event.data === hash.current.get('state')) {
        const result: IWindowMessage<IUser> = {
          type: ROUTES.ui.signInGoogle,
          payload: data,
        };
        event.source?.postMessage(result);
        window.removeEventListener('message', messageHandler);
      }
      window.close();
    };

    window.addEventListener('message', messageHandler);
  }, [data]);

  return (
    <Form>
      {errorText ? (
        <FormAlert severity="error">{errorText}</FormAlert>
      ) : (
        <Typography
          align="center"
          variant="subtitle1"
          sx={{ mt: 2, opacity: 0.75 }}
        >
          {t.loading}...
        </Typography>
      )}
    </Form>
  );
};
export default SignInGoogleForm;
