// nuxt/components/features/Auth/SignInForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormAlert from '~/components/shared/ui/Form/FormAlert.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormPassword from '~/components/shared/ui/Form/FormPassword.vue'
import FormCheckbox from '~/components/shared/ui/Form/FormCheckbox.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import FormLink from '~/components/shared/ui/Form/FormLink.vue'
import CustomModal from '~/components/shared/ui/CustomModal/CustomModal.vue'
import VerifyUserForm from '~/components/features/Auth/VerifyUserForm.vue'
import SignInGoogleLink from '~/components/features/Auth/SignInGoogleLink.vue'
import { useMainStore } from '~/store/main/main'
import authApi from '~/api/auth/authApi'

const { t, locale } = useI18n()
const route = useRoute()
const router = useRouter()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0
const password = ref('')
const passwordIsValid = (value: string) => value.length > 0
const rememberMe = ref(false)
const mainStore = useMainStore()
const { data, error, execute, pending } = authApi.signIn()
const errorText = ref<string | null>(null)
const verifyModal = ref(false)

async function submitHandler(event?: SubmitEventPromise) {
  const results = await event
  if (results?.valid === false) return

  execute({
    username: email.value,
    password: password.value,
    rememberMe: rememberMe.value,
  })
}

watch(error, () => {
  if (error.value)
    switch (error.value?.status) {
      case 410:
        errorText.value = t('userDeleted')
        break
      case 403:
        errorText.value = null
        verifyModal.value = true
        break
      case 401:
        errorText.value = t('wrongEmailOrPassword')
        break
      case undefined:
        errorText.value = null
        break
      default:
        errorText.value = getErrorText(error.value, locale.value)
    }
})

watch(data, () => {
  if (data.value) {
    mainStore.setProfile(data.value)
    router.push(
      route.query.return
        ? decodeURIComponent(String(route.query.return))
        : ROUTES.ui.home
    )
  }
})
</script>

<template>
  <Form @submit="submitHandler">
    <FormAlert v-if="errorText" :text="errorText" type="error" />
    <FormField
      v-model="email"
      :label="$t('email')"
      name="email"
      required
      :rules="[emailIsValid]"
      type="email"
    />
    <FormPassword
      v-model="password"
      :label="$t('password')"
      name="password"
      required
      :rules="[passwordIsValid]"
    />
    <FormCheckbox
      v-model="rememberMe"
      :label="$t('rememberMe')"
      name="rememberMe"
    />
    <FormButton
      block
      color="info"
      :loading="pending || Boolean(data)"
      type="submit"
    >
      {{ $t('signIn') }}
    </FormButton>
    <FormLink :href="ROUTES.ui.signUp" :text="$t('signUpText')" />
    <FormLink
      :href="ROUTES.ui.forgotPassword"
      :text="$t('forgotPasswordText')"
    />
    <SignInGoogleLink />
  </Form>
  <CustomModal v-model="verifyModal" :title="$t('verification')">
    <VerifyUserForm
      :email="email"
      @close="verifyModal = false"
      @success="submitHandler"
    />
  </CustomModal>
</template>

// next/src/features/Auth/SignInForm.tsx
import { FC, FormEvent, useEffect, useRef, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';
import { useRouter, useSearchParams } from 'next/navigation';

import Form from '@/shared/ui/Form/Form';
import FormField from '@/shared/ui/Form/FormField';
import FormCheckbox from '@/shared/ui/Form/FormCheckbox';
import FormPassword from '@/shared/ui/Form/FormPassword';
import FormButton from '@/shared/ui/Form/FormButton';
import FormLink from '@/shared/ui/Form/FormLink';
import FormAlert from '@/shared/ui/Form/FormAlert';
import CustomModal from '@/shared/ui/CustomModal/CustomModal';
import VerifyUserForm from './VerifyUserForm';
import { useAppDispatch } from '@/shared/store/hooks';
import authApi from '@/shared/api/auth/authApi';
import { setProfile } from '@/shared/store/main/main';
import SignInGoogleLink from './SignInGoogleLink';
import { getErrorText, ROUTES } from '@ap/shared';
import useLanguageRef from '@/shared/hooks/useLanguageRef';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import useTranslate from '@/shared/hooks/useTranslate';

const SignInForm: FC = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);
  const [verifyModal, setVerifyModal] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signIn, { data, error, isFetching, originalArgs }] =
    authApi.useLazySignInQuery();
  const timeout = useRef<NodeJS.Timeout>();

  const submitHandler = (event?: FormEvent<HTMLFormElement>) => {
    event?.preventDefault();

    if (email && password) {
      signIn({ username: email, password, rememberMe });
    }
  };

  useEffect(() => {
    if (isFetching) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 410:
          setErrorText(tRef.current.userDeleted);
          break;
        case 403:
          setVerifyModal(true);
          break;
        case 401:
          setErrorText(tRef.current.wrongEmailOrPassword);
          break;
        default:
          setErrorText(getErrorText(error, lRef.current));
          break;
      }
    }
  }, [error, tRef, lRef]);

  useEffect(() => {
    if (data) {
      dispatch(setProfile(data));
      router.push(
        decodeURIComponent(searchParams.get('return') || ROUTES.ui.home)
      );
    }
  }, [data, dispatch, router, searchParams]);

  useEffect(() => {
    return () => {
      clearTimeout(timeout.current);
    };
  }, []);

  return (
    <>
      <Form onSubmit={submitHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <FormPassword
          required
          name="password"
          label={t.password}
          value={password}
          onChange={(event) => setPassword(event.currentTarget.value)}
        />
        <FormCheckbox
          labelProps={{ label: t.rememberMe }}
          name="remember"
          value="remember"
          checked={rememberMe}
          onChange={() => setRememberMe(!rememberMe)}
        />
        <FormButton
          type="submit"
          fullWidth
          loading={isFetching || Boolean(data)}
        >
          {t.signIn}
        </FormButton>
        <FormLink href={ROUTES.ui.signUp} mui={{ align: 'center' }}>
          {t.signUpText}
        </FormLink>
        <FormLink href={ROUTES.ui.forgotPassword} mui={{ align: 'center' }}>
          {t.forgotPasswordText}
        </FormLink>
        <SignInGoogleLink />
      </Form>
      <CustomModal
        open={verifyModal}
        title={t.verification}
        onClose={() => setVerifyModal(false)}
      >
        <VerifyUserForm
          email={originalArgs?.username || ''}
          onClose={() => setVerifyModal(false)}
          onSuccess={() => (timeout.current = setTimeout(submitHandler, 1000))}
        />
      </CustomModal>
    </>
  );
};
export default SignInForm;
