// nuxt/components/features/Auth/SignUpSuccessForm.vue
<script setup lang="ts">
import Form from '~/components/shared/ui/Form/Form.vue'
import FormAlert from '~/components/shared/ui/Form/FormAlert.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'

defineEmits<{
  close: []
}>()
</script>

<template>
  <Form @submit="$emit('close')">
    <FormAlert :text="$t('registrationSuccessText')" type="success" />
    <FormButton block color="info" type="submit">
      {{ $t('signIn') }}
    </FormButton>
  </Form>
</template>

// next/src/features/Auth/SignUpSuccessForm.tsx
import { FC } from 'react';

import Form from '@/shared/ui/Form/Form';
import FormButton from '@/shared/ui/Form/FormButton';
import useTranslate from '@/shared/hooks/useTranslate';
import FormAlert from '@/shared/ui/Form/FormAlert';

const SignUpSuccessForm: FC<{
  onClose?: () => void;
}> = ({ onClose }) => {
  const t = useTranslate();

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onClose?.();
  };

  return (
    <Form onSubmit={submitHandler}>
      <FormAlert severity="success">{t.registrationSuccessText}</FormAlert>
      <FormButton type="submit" fullWidth>
        {t.signIn}
      </FormButton>
    </Form>
  );
};
export default SignUpSuccessForm;
