// next/src/features/Auth/ForgotPasswordForm.tsx
import { FC, useEffect, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import Form from '@/shared/ui/Form/Form';
import FormField from '@/shared/ui/Form/FormField';
import FormButton from '@/shared/ui/Form/FormButton';
import FormLink from '@/shared/ui/Form/FormLink';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/shared/ui/Form/FormAlert';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import CustomModal from '@/shared/ui/CustomModal/CustomModal';
import ResetPasswordForm from './ResetPasswordForm';
import authApi from '@/shared/api/auth/authApi';
import { makeErrorText } from '@/shared/lib/utils';

const ForgotPasswordForm: FC = () => {
  const t = useT();
  const lang = useLang();
  const [email, setEmail] = useState('');
  const [resetModal, setResetModal] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [forgotPassword, { data, error, isFetching, originalArgs }] =
    authApi.useLazyForgotPasswordQuery();

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (email) {
      forgotPassword({ email });
    }
  };

  useEffect(() => {
    if (isFetching) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(d[lang.current].wrongEmail);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data) {
      setResetModal(true);
    }
  }, [data]);

  return (
    <>
      <Form onSubmit={submitHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <FormButton type="submit" fullWidth loading={isFetching}>
          {t.confirm}
        </FormButton>
        <FormLink href={ROUTES.ui.signIn} mui={{ align: 'center' }}>
          {t.signInText}
        </FormLink>
        <FormLink href={ROUTES.ui.signUp} mui={{ align: 'center' }}>
          {t.signUpText}
        </FormLink>
      </Form>
      <CustomModal
        open={resetModal}
        title={t.resetPassword}
        onClose={() => setResetModal(false)}
      >
        <ResetPasswordForm
          email={originalArgs?.email || ''}
          onClose={() => setResetModal(false)}
        />
      </CustomModal>
    </>
  );
};
export default ForgotPasswordForm;

// nuxt/components/entities/Forms/Auth/ForgotPasswordForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/kit/Form/Form.vue'
import FormAlert from '~/components/shared/kit/Form/FormAlert.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import FormLink from '~/components/shared/kit/Form/FormLink.vue'
import CustomModal from '~/components/shared/kit/CustomModal/CustomModal.vue'
import ResetPasswordForm from '~/components/entities/Forms/Auth/ResetPasswordForm.vue'
import authApi from '~/api/auth/authApi'

const { t, locale } = useI18n()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0 || t('emailValidation')
const { data, error, execute, pending } = authApi.forgotPassword()
const errorMsg = ref<string | null>(null)
const resetModal = ref(false)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid)
    execute(email.value)
}

watch(
  error,
  () => {
    switch (error.value?.status) {
      case 404:
        errorMsg.value = t('wrongEmail')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(error.value, locale.value)
    }
  },
)

watch(
  data,
  () => {
    if (data.value)
      resetModal.value = true
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormAlert v-if="errorMsg" :text="errorMsg" type="error" />
    <FormField
v-model="email" :hint="$t('emailValidation')" :label="$t('email')" name="email" required
      :rules="[emailIsValid]" type="text" />
    <FormButton block color="success" :loading="pending || !!data" type="submit">
      {{ $t('confirm') }}
    </FormButton>
    <FormLink :href="ROUTES.auth.signIn" :text="$t('signInText')" />
    <FormLink :href="ROUTES.auth.signUp" :text="$t('signUpText')" />
    <CustomModal v-model="resetModal" :title="$t('resetPassword')">
      <ResetPasswordForm :email="email" @close="resetModal = false" />
    </CustomModal>
  </Form>
</template>
