// next/components/Forms/User/CreateUser.tsx
import React from 'react';
import { useRouter } from 'next/router';

import usersApi from '../../../store/api/usersApi';
import { useAppDispatch } from '../../../store/hooks';
import { addAlert } from '../../../store/slices/appSlice';
import FormActions from '../FormActions';
import TextFieldStyled from '../FormTextFieldStyled';
import FormBoxStyled from '../FormBoxStyled';
import FormCheckbox from '../FormCheckbox';
import { makeErrorText } from '../../../lib/functions';
import { ROUTES } from '../../../lib/constants';
import useRights from '../../../hooks/useRights';
import dictionary from '../../../locales/dictionary';
import useLang from '../../../hooks/useLang';
import useT from 'hooks/useT';

const CreateUser: React.FC = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const lang = useLang();
  const t = useT();
  const [create, createReq] = usersApi.useCreateMutation();
  const [email, setEmail] = React.useState('');
  const [name, setName] = React.useState('');
  const [password, setPassword] = React.useState('');
  const [enabled, setEnabled] = React.useState(true);
  const rights = useRights(ROUTES.api.users);

  const createHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    create({ email, name, password, enabled });
  };

  React.useEffect(() => {
    if (createReq.isLoading) {
      return;
    }
    if (createReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(createReq.error, lang.current),
        })
      );
    }
    if (createReq.data) {
      dispatch(
        addAlert({ type: 'success', text: dictionary[lang.current].success })
      );
      router.push(ROUTES.panel.user(createReq.data.id));
    }
  }, [
    createReq.data,
    createReq.error,
    createReq.isLoading,
    dispatch,
    router,
    lang,
  ]);

  return (
    <FormBoxStyled autoComplete="off" onSubmit={createHandler}>
      <TextFieldStyled
        required
        autoComplete="off"
        name="email"
        type="email"
        label={t.email}
        value={email}
        onChange={(event) => setEmail(event.currentTarget.value)}
      />
      <TextFieldStyled
        required
        autoComplete="off"
        name="name"
        type="text"
        label={t.name}
        value={name}
        onChange={(event) => setName(event.currentTarget.value)}
      />
      <TextFieldStyled
        required
        autoComplete="new-password"
        name="password"
        type="password"
        label={t.password}
        value={password}
        onChange={(event) => setPassword(event.currentTarget.value)}
      />
      <FormCheckbox
        label={t.enabled}
        name="enabled"
        value="enabled"
        checked={enabled}
        onChange={() => setEnabled(!enabled)}
      />
      <FormActions
        create={{
          loading: createReq.isLoading || Boolean(createReq.data),
          disabled: !rights.creating,
        }}
      />
    </FormBoxStyled>
  );
};
export default CreateUser;

// nuxt/components/Forms/User/CreateUser.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormTextInput from '../FormTextInput.vue'
import FormPasswordInput from '../FormPasswordInput.vue'
import FormCheckbox from '../FormCheckbox.vue'
import FormButton from '../FormButton.vue'
import { useUsersStore } from '~/stores/users'
import { useMainStore } from '~/stores/main'

const { t } = useI18n()
const email = ref('')
const emailIsValid = (value: string) => testString(EMAIL_REGEX, value) || t('emailValidation')
const name = ref('')
const nameIsValid = (value: string) => testString(NAME_REGEX, value) || t('nameValidation')
const password = ref('')
const passwordIsValid = (value: string) => testString(PASSWORD_REGEX, value) || t('passwordValidation')
const enabled = ref(true)
const usersStore = useUsersStore()
const mainStore = useMainStore()
const router = useRouter()
const rights = useRights(ROUTES.api.users)

function submitHandler() {
  if (
    emailIsValid(email.value)
    && nameIsValid(name.value)
    && passwordIsValid(password.value,
    ))
    usersStore.create({ email: email.value, name: name.value, password: password.value, enabled: enabled.value })
}

watch(
  () => usersStore.createPending,
  () => {
    if (usersStore.createPending === true)
      return
    if (usersStore.createError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(usersStore.createError) })
    if (usersStore.createData) {
      mainStore.addAlert({ type: 'success', text: t('success') })
      router.push(ROUTES.panel.user(usersStore.createData.id))
    }
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <FormTextInput
      v-model:model-value="email" type="email" required name="email" :label="$t('email')"
      :rules="[emailIsValid]" :hint="$t('emailValidation')"
    />
    <FormTextInput
      v-model:model-value="name" required name="name" :label="$t('name')"
      :rules="[nameIsValid]" :hint="$t('nameValidation')"
    />
    <FormPasswordInput
      v-model:model-value="password" required name="password" :label="$t('password')"
      :rules="[passwordIsValid]" :hint="$t('passwordValidation')"
    />
    <FormCheckbox v-model:model-value="enabled" name="enabled" :label="$t('enabled')" />
    <FormButton type="submit" color="info" prepand-icon="mdi-plus" :loading="usersStore.createPending" :disabled="!rights.creating">
      {{ $t('create') }}
    </FormButton>
  </FormBox>
</template>
