// nuxt/components/features/Profile/ChangeEmailConfirmForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import profileApi from '~/api/profile/profileApi'
import { useMainStore } from '~/store/main/main'

const { email } = defineProps<{
  email: string
}>()
const emit = defineEmits<{
  close: []
}>()

const { t, locale } = useI18n()
const mainStore = useMainStore()
const code = ref('')
const codeIsValid = (value: string) => value.length > 0 || `${t('codeFromEmail')} (${email})`
const { data, error, execute, pending } = profileApi.changeEmailConfirm()
const rights = useRights(ROUTES.api.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid)
    execute(code.value)
}

watch(
  error,
  () => {
    if (error.value)
      switch (error.value?.status) {
        case 404:
          mainStore.addAlert({ type: 'error', text: t('wrongEmailOrCode') })
          break
        default:
          mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })
      }
  },
)

watch(
  data,
  () => {
    if (data.value) {
      emit('close')
      if (mainStore.profile)
        mainStore.setProfile({ ...mainStore.profile, email })
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormField
v-model="code" :hint="`${$t('codeFromEmail')} (${email})`" :label="$t('code')" name="code" required
      :rules="[codeIsValid]" />
    <FormButton block color="success" :disabled="!rights.updating" :loading="pending || Boolean(data)" type="submit">
      {{ $t('confirm') }}
    </FormButton>
    <FormButton block color="error" type="button" @click="$emit('close')">
      {{ $t('close') }}
    </FormButton>
  </Form>
</template>

// apps/frontend/panel-react/src/features/Profile/ChangeEmailConfirmForm.tsx
import { FC, useEffect, useRef, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import FormBase from '@/shared/ui/Form/FormBase';
import FormButton from '@/shared/ui/Form/FormButton';
import FormField from '@/shared/ui/Form/FormField';
import { useAppDispatch, useAppSelector } from '@/shared/store/hooks';
import { addAlert, setProfile } from '@/shared/store/main/main';
import useRights from '@/shared/hooks/useRights';
import profileApi from '@/shared/api/profile/profileApi';
import { getErrorText, ROUTES } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const ChangeEmailConfirmForm: FC<{
  email: string;
  onClose?: () => void;
}> = ({ email, onClose }) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [changeEmailConfirm, { isSuccess, error, isLoading }] =
    profileApi.useChangeEmailConfirmMutation();
  const rights = useRights(ROUTES.api.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const emailRef = useRef(email);
  const profileRef = useRef(profile);
  const [code, setCode] = useState('');

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    changeEmailConfirm({ code });
  };

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          dispatch(
            addAlert({
              type: 'error',
              text: tRef.current.wrongEmailOrCode,
            })
          );
          break;
        default:
          dispatch(
            addAlert({
              type: 'error',
              text: getErrorText(error, lRef.current),
            })
          );
          break;
      }
    }
  }, [error, tRef, lRef, dispatch]);

  useEffect(() => {
    if (isSuccess) {
      onClose?.();

      if (profileRef.current) {
        dispatch(
          setProfile({ ...profileRef.current, email: emailRef.current })
        );
      }
    }
  }, [isSuccess, onClose, dispatch]);

  useEffect(() => {
    profileRef.current = profile;
  }, [profile]);

  return (
    <FormBase onSubmit={submitHandler}>
      <FormField
        required
        autoComplete="off"
        name="code"
        label={t.code}
        value={code}
        onChange={(event) => setCode(event.target.value)}
        helperText={`${t.codeFromEmail} (${email})`}
      />
      <FormButton
        type="submit"
        fullWidth
        disabled={!rights.updating}
        loading={isLoading || isSuccess}
      >
        {t.confirm}
      </FormButton>
      <FormButton fullWidth color="error" onClick={onClose}>
        {t.close}
      </FormButton>
    </FormBase>
  );
};
export default ChangeEmailConfirmForm;
