// nuxt/components/features/Profile/ProfileSessions.vue
<script setup lang="ts">
import SessionForm from '~/components/features/Profile/SessionForm.vue'
import { useMainStore } from '~/store/main/main'
import profileApi from '~/api/profile/profileApi'

const { locale } = useI18n()
const { data, error, execute, pending } = profileApi.getSessions()
const mainStore = useMainStore()
const sessions = ref<IExternalSession[] | null>(null)

watch(data, () => {
  sessions.value =
    data.value &&
    Array.from(data.value).sort((a, b) => (!a.current && b.current ? 1 : -1))
})

watch(error, () => {
  if (error.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
})

onMounted(() => {
  execute()
})
</script>

<template>
  <v-skeleton-loader v-if="pending" height="68" />
  <SessionForm
v-for="session of sessions" :key="session.id" :session="session" @delete="
    sessions = sessions?.filter((item) => item.id !== session.id) || null
    " />
</template>

// apps/frontend/panel-react/src/features/Profile/ProfileSessions.tsx
'use client';

import { FC, useEffect, useState } from 'react';
import Skeleton from '@mui/material/Skeleton';

import SessionForm from '@/features/Profile/SessionForm';
import { addAlert } from '@/shared/store/main/main';
import { useAppDispatch } from '@/shared/store/hooks';
import profileApi from '@/shared/api/profile/profileApi';
import useLanguageRef from '@/shared/hooks/useLanguageRef';
import { getErrorText, TExternalSession } from '@ap/shared';

const ProfileSessions: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const { data, isLoading, error } = profileApi.useGetSessionsQuery();
  const [sessions, setSessions] = useState<TExternalSession[]>();

  useEffect(() => {
    setSessions(
      data &&
        Array.from(data).sort((a, b) => (!a.current && b.current ? 1 : -1))
    );
  }, [data]);

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  return (
    <>
      {isLoading && (
        <Skeleton variant="rounded" width="100%" height={56} sx={{ mb: 1 }} />
      )}
      {sessions?.map((session) => (
        <SessionForm
          key={session.id}
          session={session}
          onDelete={() =>
            setSessions(sessions.filter((item) => item.id !== session.id))
          }
        />
      ))}
    </>
  );
};
export default ProfileSessions;
