// apps/frontend/panel-vue/components/features/Profile/SessionForm.vue
<script setup lang="ts">
import { UAParser } from 'ua-parser-js'

import authApi from '~/components/entities/auth/authApi'
import profileApi from '~/components/entities/profile/profileApi'

const props = defineProps<{
  session: TSessionExternal
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const router = useRouter()
const rights = useRights(ROUTES.api.profile)
const mainStore = useMainStore()
const userAgent = new UAParser(props.session.userAgent).getResult()
const updatedAt = getDateString(props.session.updatedAt)
const { status: dsStatus, error: dsError, execute: dsExecute } = profileApi.deleteSessions({ items: [props.session.id] })
const { status: soStatus, error: soError, execute: soExecute } = authApi.signOut()

async function submitHandler() {
  if (props.session.current) {
    soExecute()
  }
  else {
    dsExecute()
  }
}

watch(dsError, () => {
  if (!dsError.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(dsError.value, locale.value),
  })
})

watch(dsStatus, () => {
  if (dsStatus.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(soError, () => {
  if (!soError.value) {
    return
  }

  if (soError.value.statusCode === 401) {
    router.push(ROUTES.ui.signIn)
  }
  else {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(soError.value, locale.value),
    })
  }
})

watch(soStatus, () => {
  if (soStatus.value === 'success') {
    router.push(ROUTES.ui.signIn)
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <v-card class="mb-1 d-flex flex-row">
      <v-card-text class="d-flex flex-row align-center">
        <template v-if="userAgent.device.vendor">
          <v-icon
            class="mr-1"
            icon="mdi-cellphone"
          />
          <span class="text-body-2">
            {{ userAgent.device.vendor }}{{ ' ' }} {{ userAgent.device.model
            }}{{ ',' }}&nbsp;
          </span>
        </template>
        <template v-else>
          <v-icon
            class="mr-1"
            icon="mdi-laptop"
          />
          <span class="text-body-2">
            {{ userAgent.os.name }} {{ userAgent.os.version }}{{ ',' }}&nbsp;
          </span>
        </template>
        <span class="text-body-2">
          {{ userAgent.browser.name }} {{ userAgent.browser.version
          }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-80">
          {{ session.ip }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-60 mr-2">
          {{ updatedAt }}
        </span>
        <v-chip
          v-if="session.current"
          color="success"
          variant="outlined"
        >
          {{
            $t('current')
          }}
        </v-chip>
      </v-card-text>
      <v-card-actions>
        <v-btn
          color="error"
          :disabled="!rights.updating || dsStatus === 'pending' || dsStatus === 'success'"
          icon="mdi-delete"
          type="submit"
          variant="text"
        />
      </v-card-actions>
    </v-card>
  </FormBase>
</template>

// apps/frontend/panel-react/src/features/Profile/SessionForm.tsx
import { FC, FormEvent, useEffect, useRef } from "react";
import { UAParser } from "ua-parser-js";
import DeleteIcon from "@mui/icons-material/Delete";
import ComputerIcon from "@mui/icons-material/Computer";
import SmartphoneIcon from "@mui/icons-material/Smartphone";
import {
  Card,
  CardActions,
  CardContent,
  Chip,
  IconButton,
  styled,
  Typography,
} from "@mui/material";

import FormBase from "@/shared/ui/Form/FormBase";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert, setProfile } from "@/app/store/main/main";
import theme from "@/shared/lib/theme";
import useRights from "@/shared/hooks/useRights";
import useTranslate from "@/shared/hooks/useTranslate";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import { TSessionExternal } from "@ap/shared/dist/types";
import { getDateString, getErrorText, ROUTES } from "@ap/shared/dist/libs";
import profileApi from "@/entities/profile/api";

const SessionForm: FC<{ session: TSessionExternal; onDelete?: () => void }> = ({
  session,
  onDelete,
}) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const rights = useRights(ROUTES.api.profile);
  const userAgent = useRef(new UAParser(session.userAgent).getResult());
  const [remove, removeReq] = profileApi.useDeleteSessionsMutation();

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    remove({ items: [session.id] });
  };

  useEffect(() => {
    if (removeReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(removeReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, removeReq.error, lRef]);

  useEffect(() => {
    if (removeReq.isSuccess) {
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
      onDelete?.();

      if (session.current) {
        dispatch(setProfile(null));
      }
    }
  }, [removeReq.isSuccess, dispatch, session, tRef, onDelete]);

  return (
    <FormBase onSubmit={submitHandler}>
      <Session>
        <SessionContent>
          {userAgent.current.device.vendor ? (
            <>
              <SmartphoneIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.device.vendor}{" "}
                {userAgent.current.device.model}
                {","}&nbsp;
              </Typography>
            </>
          ) : (
            <>
              <ComputerIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.os.name} {userAgent.current.os.version}
                {","}&nbsp;
              </Typography>
            </>
          )}
          <Typography component="span" variant="body2">
            {userAgent.current.browser.name} {userAgent.current.browser.version}
            {","}&nbsp;
          </Typography>
          <Typography component="span" variant="body2" sx={{ opacity: 0.8 }}>
            {session.ip}
            {","}&nbsp;
          </Typography>
          <Typography
            component="span"
            variant="body2"
            sx={{ mr: 1, opacity: 0.6 }}
          >
            {getDateString(session.updatedAt)}
          </Typography>
          {session.current && (
            <Chip
              label={t.current}
              color="success"
              variant="outlined"
              size="small"
            />
          )}
        </SessionContent>
        <CardActions sx={{ pr: 2 }}>
          <IconButton
            edge="end"
            color="error"
            aria-label="sign out"
            title={t.signOut}
            disabled={
              !rights.updating || removeReq.isLoading || removeReq.isSuccess
            }
            type="submit"
          >
            <DeleteIcon />
          </IconButton>
        </CardActions>
      </Session>
    </FormBase>
  );
};
export default SessionForm;

const Session = styled(Card)`
  display: flex;
  flex-direction: row;
  margin-bottom: ${theme.spacing(1)};
`;

const SessionContent = styled(CardContent)`
  flex-grow: 1;
  display: flex;
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
`;
