// nuxt/components/features/Profile/SessionForm.vue
<script setup lang="ts">
import UAParser from 'ua-parser-js'

import Form from '~/components/shared/ui/Form/Form.vue'
import { useMainStore } from '~/store/main/main'
import profileApi from '~/api/profile/profileApi'
import type { IExternalSession } from '~/api/profile/types'

const { session } = defineProps<{ session: IExternalSession }>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const mainStore = useMainStore()
const { data, error, execute, pending } = profileApi.deleteSessions()
const rights = useRights(ROUTES.api.profile)
const userAgent = new UAParser(session.userAgent).getResult()
const updatedAt = makeDateString(session.updatedAt)

async function submitHandler() {
  execute({items: [session.id]})
}

watch(
  error,
  () => {
    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })
  },
)

watch(
  data,
  () => {
    if (data.value) {
      mainStore.addAlert({ type: 'success', text: t('success') })
      emit('delete')

      if (session.current) {
        mainStore.setProfile(null)
      }
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <v-card class="mb-1 d-flex flex-row">
      <v-card-text class="d-flex flex-row align-center">
        <template v-if="userAgent.device.vendor">
          <v-icon class="mr-1" icon="mdi-cellphone" />
          <span class="text-body-2">
            {{ userAgent.device.vendor }}{{ ' ' }}
            {{ userAgent.device.model }}{{ ',' }}&nbsp;
          </span>
        </template>
        <template v-else>
          <v-icon class="mr-1" icon="mdi-laptop" />
          <span class="text-body-2">
            {{ userAgent.os.name }} {{ userAgent.os.version }}{{ ',' }}&nbsp;
          </span>
        </template>
        <span class="text-body-2">
          {{ userAgent.browser.name }} {{ userAgent.browser.version }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-80">
          {{ session.ip }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-60 mr-2">
          {{ updatedAt }}
        </span>
        <v-chip v-if="session.current" color="success" variant="outlined">{{ $t('current') }}</v-chip>
      </v-card-text>
      <v-card-actions>
        <v-btn
color="error" :disabled="!rights.updating || pending || Boolean(data)" icon="mdi-delete" type="submit"
          variant="text" />
      </v-card-actions>
    </v-card>
  </Form>
</template>

// apps/frontend/panel-react/src/features/Profile/SessionForm.tsx
import { FC, FormEvent, useEffect, useRef } from 'react';
import { UAParser } from 'ua-parser-js';
import DeleteIcon from '@mui/icons-material/Delete';
import ComputerIcon from '@mui/icons-material/Computer';
import SmartphoneIcon from '@mui/icons-material/Smartphone';
import {
  Card,
  CardActions,
  CardContent,
  Chip,
  IconButton,
  styled,
  Typography,
} from '@mui/material';

import FormBase from '@/shared/ui/Form/FormBase';
import { useAppDispatch } from '@/shared/store/hooks';
import { addAlert, setProfile } from '@/shared/store/main/main';
import theme from '@/shared/lib/theme';
import useRights from '@/shared/hooks/useRights';
import profileApi from '@/shared/api/profile/profileApi';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import { TExternalSession } from '@ap/shared/src/types';
import { getDateString, getErrorText, ROUTES } from '@ap/shared/src/libs';

const SessionForm: FC<{ session: TExternalSession; onDelete?: () => void }> = ({
  session,
  onDelete,
}) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const rights = useRights(ROUTES.api.profile);
  const userAgent = useRef(new UAParser(session.userAgent).getResult());
  const [remove, removeReq] = profileApi.useDeleteSessionsMutation();

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    remove({ items: [session.id] });
  };

  useEffect(() => {
    if (removeReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(removeReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, removeReq.error, lRef]);

  useEffect(() => {
    if (removeReq.isSuccess) {
      dispatch(addAlert({ type: 'success', text: tRef.current.success }));
      onDelete?.();

      if (session.current) {
        dispatch(setProfile(null));
      }
    }
  }, [removeReq.isSuccess, dispatch, session, tRef, onDelete]);

  return (
    <FormBase onSubmit={submitHandler}>
      <Session>
        <SessionContent>
          {userAgent.current.device.vendor ? (
            <>
              <SmartphoneIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.device.vendor}{' '}
                {userAgent.current.device.model}
                {','}&nbsp;
              </Typography>
            </>
          ) : (
            <>
              <ComputerIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.os.name} {userAgent.current.os.version}
                {','}&nbsp;
              </Typography>
            </>
          )}
          <Typography component="span" variant="body2">
            {userAgent.current.browser.name} {userAgent.current.browser.version}
            {','}&nbsp;
          </Typography>
          <Typography component="span" variant="body2" sx={{ opacity: 0.8 }}>
            {session.ip}
            {','}&nbsp;
          </Typography>
          <Typography
            component="span"
            variant="body2"
            sx={{ mr: 1, opacity: 0.6 }}
          >
            {getDateString(session.updatedAt)}
          </Typography>
          {session.current && (
            <Chip
              label={t.current}
              color="success"
              variant="outlined"
              size="small"
            />
          )}
        </SessionContent>
        <CardActions sx={{ pr: 2 }}>
          <IconButton
            edge="end"
            color="error"
            aria-label="sign out"
            title={t.signOut}
            disabled={
              !rights.updating || removeReq.isLoading || removeReq.isSuccess
            }
            type="submit"
          >
            <DeleteIcon />
          </IconButton>
        </CardActions>
      </Session>
    </FormBase>
  );
};
export default SessionForm;

const Session = styled(Card)`
  display: flex;
  flex-direction: row;
  margin-bottom: ${theme.spacing(1)};
`;

const SessionContent = styled(CardContent)`
  flex-grow: 1;
  display: flex;
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
`;
