// nuxt/components/features/Resources/ResourcesList.vue
<script setup lang="ts">
import resourcesApi from '~/api/resources/resourcesApi'
import ResourcesTable from '~/components/entities/Resource/ResourcesTable.vue'
import { useMainStore } from '~/store/main/main'

const props = defineProps<{
  rows?: IResource[];
  count?: number;
  page?: number;
  quantity?: number;
}>()
defineEmits<{
  'update:page': [value: number];
  'update:quantity': [value: number];
}>()

const { locale } = useI18n()
const {
  data: faData,
  error: faError,
  execute: faExecute,
  pending: faPending,
} = resourcesApi.getList()
const {
  data: dData,
  error: dError,
  execute: dExecute,
  pending: dPending,
} = resourcesApi.delete()
const page = ref(props.page || 1)
const quantity = ref(props.quantity || 25)
const count = computed(
  () => faData.value?.count || props.count || page.value * quantity.value
)
const items = ref(props.rows)
const rights = useRights(ROUTES.api.resources)
const mainStore = useMainStore()
const selected = ref<string[]>([])

watch(
  () => props.rows,
  () => {
    if (!props.rows) {
      faExecute({
        reqPage: page.value,
        reqLimit: quantity.value,
        reqCount: true,
      })
    }
  },
  { immediate: true }
)

watch([page, quantity], () => {
  faExecute({ reqPage: page.value, reqLimit: quantity.value })
})

watch(faData, () => {
  if (faData.value) items.value = faData.value.rows
})

watch(faError, () => {
  if (faError.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(faError.value, locale.value),
    })
})

watch(dData, () => {
  if (dData.value) {
    faExecute({
      reqPage: page.value,
      reqLimit: quantity.value,
      reqCount: true,
    })
  }
})

watch(dError, () => {
  if (dError.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(dError.value, locale.value),
    })
})
</script>

<template>
  <div class="mb-3">
    <NuxtLink :href="rights.creating ? ROUTES.ui.newResource : undefined">
      <v-btn class="me-2" color="info" :disabled="!rights.creating" prepend-icon="mdi-plus" variant="flat">
        {{ $t('create') }}
      </v-btn>
    </NuxtLink>
    <v-btn
color="error" :disabled="!rights.deleting || selected.length === 0" :loading="dPending"
      prepend-icon="mdi-delete" variant="flat" @click="dExecute({ items: selected })">
      {{ $t('delete') }}
    </v-btn>
  </div>
  <ResourcesTable
v-model:page="page" v-model:quantity="quantity" v-model:selected="selected" :count="count"
    :loading="dPending || faPending" :rows="items" @update:page="$emit('update:page', $event)"
    @update:quantity="$emit('update:quantity', $event)" />
</template>

// apps/frontend/panel-react/src/features/Resources/ResourcesList.tsx
'use client';

import { FC, useEffect, useMemo, useRef, useState } from 'react';
import DeleteIcon from '@mui/icons-material/Delete';
import AddIcon from '@mui/icons-material/Add';
import { GridPaginationModel } from '@mui/x-data-grid/models';

import ResourcesTable from '@/entities/Resources/ResourcesTable';
import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import resourcesApi from '@/shared/api/resources/resourcesApi';
import { IList } from '@/shared/lib/types';
import { useAppDispatch } from '@/shared/store/hooks';
import { addAlert } from '@/shared/store/main/main';
import { getErrorText, IResource, ROUTES } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const ResourcesList: FC<IList<IResource>> = (props) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const t = useTranslate();
  const rights = useRights(ROUTES.api.resources);
  const [getList, getListReq] = resourcesApi.useLazyGetListQuery();
  const [destroy, destroyReq] = resourcesApi.useDeleteMutation();
  const [selectedRows, setSelectedRows] = useState<string[]>([]);
  const [items, setItems] = useState(props.rows);
  const paginationModel = useRef<GridPaginationModel>({
    page: (props.page || 1) - 1,
    pageSize: props.limit || 25,
  });
  const count = useMemo(
    () =>
      getListReq.data?.count ||
      props.count ||
      paginationModel.current.page * paginationModel.current.pageSize,
    [props.count, getListReq.data]
  );

  const paginationHandler = (model: GridPaginationModel) => {
    getList({ reqPage: model.page + 1, reqLimit: model.pageSize });

    if (props.onPageUpdate && model.page !== paginationModel.current.page) {
      props.onPageUpdate(model.page + 1);
    }

    if (
      props.onLimitUpdate &&
      model.pageSize !== paginationModel.current.pageSize
    ) {
      props.onLimitUpdate(model.pageSize);
    }

    paginationModel.current = model;
  };

  useEffect(() => {
    if (!props.rows) {
      getList({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [props.rows, getList]);

  useEffect(() => {
    if (destroyReq.isSuccess) {
      getList({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [destroyReq.isSuccess, getList]);

  useEffect(() => {
    if (destroyReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(destroyReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, destroyReq.error, lRef]);

  useEffect(() => {
    if (getListReq.data) {
      setItems(getListReq.data.rows);
    }
  }, [getListReq.data]);

  useEffect(() => {
    if (getListReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(getListReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, getListReq.error, lRef]);

  useEffect(() => {
    if (getListReq.data?.rows) {
      setItems(getListReq.data?.rows);
    }
  }, [getListReq.data]);

  useEffect(() => {
    if (getListReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(getListReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, getListReq.error, lRef]);

  return (
    <>
      <FormButton
        color="primary"
        startIcon={<AddIcon />}
        disabled={!rights.creating}
        href={ROUTES.ui.newResource}
      >
        {t.create}
      </FormButton>
      <FormButton
        color="error"
        startIcon={<DeleteIcon />}
        disabled={
          !rights.deleting || selectedRows.length === 0 || destroyReq.isLoading
        }
        onClick={() => destroy({ items: selectedRows })}
      >
        {t.delete}
      </FormButton>
      <ResourcesTable
        initialState={{
          pagination: {
            paginationModel: paginationModel.current,
          },
        }}
        rows={items}
        rowCount={count}
        loading={getListReq.isLoading || destroyReq.isLoading}
        onRowSelectionModelChange={(rowSelectionModel) =>
          setSelectedRows(rowSelectionModel.ids.values().toArray() as string[])
        }
        onPaginationModelChange={paginationHandler}
      />
    </>
  );
};
export default ResourcesList;
