// next/src/features/Auth/SignInGoogleLink.tsx
import { FC, MouseEventHandler, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

import FormLink from '@/shared/ui/Form/FormLink';
import { ROUTES } from '@/shared/lib/constants';
import { useAppDispatch } from '@/shared/store/hooks';
import { setProfile } from '@/shared/store/main/main';
import { getGoogleSignInUrl } from './utils';
import useT from '@/shared/hooks/useT';
import { IWindowMessage } from './types';
import { IUser } from '@/shared/api/users/types';

const SignInGoogleLink: FC = () => {
  const t = useT();
  const router = useRouter();
  const searchParams = useSearchParams();
  const dispatch = useAppDispatch();
  const timeout = useRef<NodeJS.Timeout>();

  const googleHandler: MouseEventHandler<HTMLAnchorElement> = (event) => {
    event.preventDefault();
    const state = String(Math.random());
    const googleWindow = window.open(
      getGoogleSignInUrl(state),
      undefined,
      'top=100,left=100,width=500,height=500'
    );
    clearTimeout(timeout.current);
    timeout.current = setInterval(() => {
      googleWindow?.postMessage(state);
    }, 1000);
  };

  useEffect(() => {
    const messageHandler = (event: MessageEvent<IWindowMessage<IUser>>) => {
      if (event.data.type !== ROUTES.ui.signInGoogle) return;
      dispatch(setProfile(event.data.payload));
      router.push(
        decodeURIComponent(searchParams.get('return') || ROUTES.ui.home)
      );
    };

    window.addEventListener('message', messageHandler);

    return () => {
      window.removeEventListener('message', messageHandler);
    };
  }, [dispatch, router, searchParams]);

  useEffect(() => {
    return () => {
      clearTimeout(timeout.current);
    };
  }, []);

  return (
    <FormLink
      onClick={googleHandler}
      href={ROUTES.ui.signInGoogle}
      mui={{ align: 'center' }}
    >
      {t.signInWithGoogle}
    </FormLink>
  );
};
export default SignInGoogleLink;

// nuxt/components/features/Auth/SignInGoogleLink.vue
<script setup lang="ts">
import { useMainStore } from '~/store/main/main'
import FormLink from '~/components/shared/ui/Form/FormLink.vue'
import { getGoogleSignInUrl } from './utils'
import type { IWindowMessage } from './types'
import type { IUser } from '~/api/users/types'

const route = useRoute()
const router = useRouter()
const mainStore = useMainStore()
const timeout = ref<NodeJS.Timeout>()

const googleHandler = (event: MouseEvent) => {
  event.preventDefault()
  const state = String(Math.random())
  const googleWindow = window.open(
    getGoogleSignInUrl(state),
    undefined,
    'top=100,left=100,width=500,height=500'
  )
  clearTimeout(timeout.value)
  timeout.value = setInterval(() => {
    googleWindow?.postMessage(state)
  }, 1000)
}

const messageHandler = (event: MessageEvent<IWindowMessage<IUser>>) => {
  if (event.data.type !== ROUTES.ui.signInGoogle) return
  mainStore.setProfile(event.data.payload)
  router.push(route.query.return ? decodeURIComponent(String(route.query.return)) : ROUTES.ui.home)
}

onMounted(() => {
  window.addEventListener('message', messageHandler)
})

onUnmounted(() => {
  window.removeEventListener('message', messageHandler)
  clearTimeout(timeout.value)
})
</script>

<template>
  <FormLink event="" :href="ROUTES.ui.signInGoogle" :text="$t('signInWithGoogle')" @click="googleHandler" />
</template>
