// apps/frontend/panel-react/src/features/Auth/VerifyUserForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import FormBase from '@/shared/ui/Form/FormBase';
import FormField from '@/shared/ui/Form/FormField';
import FormButton from '@/shared/ui/Form/FormButton';
import FormAlert from '@/shared/ui/Form/FormAlert';
import authApi from '@/shared/api/auth/authApi';
import { getErrorText } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const VerifyUserForm: FC<{
  email: string;
  onClose?: () => void;
  onSuccess?: () => void;
}> = ({ email, onClose, onSuccess }) => {
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [verifyUser, { isSuccess, error, isFetching }] =
    authApi.useLazyVerifyUserQuery();
  const [errorText, setErrorText] = useState<string | null>(null);
  const [code, setCode] = useState('');

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    verifyUser({ email, code });
  };

  useEffect(() => {
    if (isFetching) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(tRef.current.wrongCode);
          break;
        default:
          setErrorText(getErrorText(error, lRef.current));
          break;
      }
    }
  }, [error, lRef, tRef]);

  useEffect(() => {
    if (isSuccess) {
      onClose?.();
      onSuccess?.();
    }
  }, [isSuccess, onClose, onSuccess]);

  return (
    <FormBase onSubmit={submitHandler}>
      {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
      <FormField
        required
        autoComplete="off"
        name="code"
        label={t.code}
        value={code}
        onChange={(event) => setCode(event.target.value)}
        helperText={`${t.codeFromEmail} (${email})`}
      />
      <FormButton type="submit" fullWidth loading={isFetching || isSuccess}>
        {t.confirm}
      </FormButton>
      <FormButton color="error" onClick={onClose} fullWidth>
        {t.close}
      </FormButton>
    </FormBase>
  );
};
export default VerifyUserForm;

// nuxt/components/features/Auth/VerifyUserForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormAlert from '~/components/shared/ui/Form/FormAlert.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import authApi from '~/api/auth/authApi'

const { email } = defineProps<{
  email: string
}>()
const emit = defineEmits<{
  close: []
  success: []
}>()

const { t, locale } = useI18n()
const code = ref('')
const codeIsValid = (value: string) => value.length > 0 || `${t('codeFromEmail')} (${email})`
const { data, error, execute, pending } = authApi.verifyUser()

const errorText = ref<string | null>(null)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid)
    execute({ email: email, code: code.value })
}

watch(
  error,
  () => {
    if (error.value)
      switch (error.value?.status) {
        case 404:
          errorText.value = t('wrongCode')
          break
        case undefined:
          errorText.value = null
          break
        default:
          errorText.value = makeErrorText(error.value, locale.value)
      }
  },
)

watch(
  data,
  () => {
    if (data.value) {
      emit('close')
      emit('success')
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormAlert v-if="errorText" :text="errorText" type="error" />
    <FormField
v-model="code" :hint="`${$t('codeFromEmail')} (${email})`" :label="$t('code')" name="code" required
      :rules="[codeIsValid]" />
    <FormButton block color="success" :loading="pending || Boolean(data)" type="submit">
      {{ $t('confirm') }}
    </FormButton>
    <FormButton block color="error" type="button" @click="$emit('close')">
      {{ $t('close') }}
    </FormButton>
  </Form>
</template>
