// nuxt/components/features/Resources/ResourceRightsFields.vue
<script setup lang="ts">
import type { IResource, IRolesResources } from '~/api/resources/types'
import FormCheckbox from '~/components/shared/ui/Form/FormCheckbox.vue'

const { roleId, resource, rights } = defineProps<{ roleId: number, resource: IResource, rights?: IRolesResources }>()
const emit = defineEmits<{
  update: [value: IRolesResources]
}>()

const newRights = ref(rights || {
  roleId,
  resourceId: resource.id,
  creating: false,
  reading: false,
  updating: false,
  deleting: false,
})

function updateHandler(permisson: keyof Omit<IRolesResources, 'roleId' | 'resourceId'>, value: boolean) {
  newRights.value = { ...newRights.value, [permisson]: value }
  emit('update', newRights.value)
}
</script>

<template>
  <fieldset class="fieldset mr-6">
    <v-card-subtitle class="px-0 pt-0 pb-3" tag="legend">
      {{ resource.name }}
    </v-card-subtitle>
    <v-card-text class="px-0 pt-0 pb-3" tag="legend">
      {{ resource.description }}
    </v-card-text>
    <FormCheckbox
:label="$t('create')" :model-value="newRights.creating" :name="`${resource.name}.creating`"
      @update:model-value="updateHandler('creating', $event)" />
    <FormCheckbox
:label="$t('read')" :model-value="newRights.reading" :name="`${resource.name}.reading`"
      @update:model-value="updateHandler('reading', $event)" />
    <FormCheckbox
:label="$t('update')" :model-value="newRights.updating" :name="`${resource.name}.updating`"
      @update:model-value="updateHandler('updating', $event)" />
    <FormCheckbox
:label="$t('delete')" :model-value="newRights.deleting" :name="`${resource.name}.deleting`"
      @update:model-value="updateHandler('deleting', $event)" />
  </fieldset>
</template>

<style scoped lang="scss">
.fieldset {
  border-style: unset;
}
</style>

// next/src/features/Resources/ResourceRightsFields.tsx
import React from 'react';
import {
  FormControl,
  FormGroup,
  FormHelperText,
  FormLabel,
} from '@mui/material';

import useT from '@/shared/hooks/useT';
import FormCheckbox from '@/shared/ui/Form/FormCheckbox';
import { IResource, IRolesResources } from '@/shared/api/resources/types';

const ResourceRightsFields: React.FC<{
  roleId: string;
  resource: IResource;
  rights?: IRolesResources;
  setRights: (newRights: IRolesResources) => void;
}> = ({ roleId, resource, rights, setRights }) => {
  const t = useT();
  const newRights: IRolesResources = rights || {
    roleId,
    resourceId: resource.id,
    creating: false,
    reading: false,
    updating: false,
    deleting: false,
  };

  return (
    <FormControl sx={{ my: 1, mr: 3 }} component="fieldset" variant="standard">
      <FormLabel component="legend">{resource.name}</FormLabel>
      <FormGroup>
        <FormCheckbox
          labelProps={{ label: t.create }}
          name="create[]"
          value="create"
          checked={rights?.creating || false}
          onChange={() =>
            setRights({ ...newRights, creating: !newRights.creating })
          }
        />
        <FormCheckbox
          labelProps={{ label: t.read }}
          name="read[]"
          value="read"
          checked={rights?.reading || false}
          onChange={() =>
            setRights({ ...newRights, reading: !newRights.reading })
          }
        />
        <FormCheckbox
          labelProps={{ label: t.update }}
          name="update[]"
          value="update"
          checked={rights?.updating || false}
          onChange={() =>
            setRights({ ...newRights, updating: !newRights.updating })
          }
        />
        <FormCheckbox
          labelProps={{ label: t.delete }}
          name="delete[]"
          value="delete"
          checked={rights?.deleting || false}
          onChange={() =>
            setRights({ ...newRights, deleting: !newRights.deleting })
          }
        />
      </FormGroup>
      <FormHelperText sx={{ maxWidth: 300 }}>
        {resource.description}
      </FormHelperText>
    </FormControl>
  );
};
export default ResourceRightsFields;
