// nuxt/components/Forms/Auth/ForgotPassword.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormAlert from '../FormAlert.vue'
import FormTextInput from '../FormTextInput.vue'
import FormButton from '../FormButton.vue'
import FormAuthLink from '../FormAuthLink.vue'
import CustomModal from '~/components/Other/CustomModal.vue'
import ResetPassword from '~/components/Forms/Auth/ResetPassword.vue'
import { makeErrorText } from '~/libs/functions'
import { ROUTES } from '~/libs/constants'
import { useProfileStore } from '~/stores/profile'

const { t } = useI18n()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0
const profileStore = useProfileStore()
const errorMsg = ref<string | null>(null)
const resetModal = ref(false)
const router = useRouter()

function submitHandler() {
  if (emailIsValid(email.value) === true)
    profileStore.forgotPassword(email.value)
}

watch(
  () => profileStore.forgotPasswordError,
  () => {
    switch (profileStore.forgotPasswordError?.status) {
      case 404:
        errorMsg.value = t('wrongEmail')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(profileStore.forgotPasswordError?.message)
    }
  },
)

watch(
  () => profileStore.forgotPasswordData,
  () => {
    if (profileStore.forgotPasswordData)
      resetModal.value = true
  },
)

watch(
  () => profileStore.resetPasswordData,
  () => {
    if (profileStore.resetPasswordData)
      router.push(ROUTES.auth.signIn)
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <FormAlert v-if="errorMsg" :title="$t('error')" :text="errorMsg" type="error" />
    <FormTextInput
      v-model:model-value="email" required name="email" type="text" :label="$t('email')"
      :rules="[emailIsValid]" :hint="$t('emailValidation')"
    />
    <FormButton block type="submit" color="success" :loading="profileStore.forgotPasswordPending">
      {{ $t('confirm') }}
    </FormButton>
    <FormAuthLink :href="ROUTES.auth.signUp" :text="$t('signUpText')" />
    <FormAuthLink :href="ROUTES.auth.signIn" :text="$t('signInText')" />
    <CustomModal v-model="resetModal" :title="$t('resetPassword')">
      <ResetPassword :email="email" @close="resetModal = false" />
    </CustomModal>
  </FormBox>
</template>

// next/components/Forms/Auth/ForgotPassword.tsx
import React from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/dist/query';

import lang from '../../../libs/lang';
import authApi from '../../../store/api/authApi';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { makeErrorText } from '../../../libs/functions';
import AuthLinkStyled from '../../../components/AuthLayout/AuthLinkStyled';
import TextFieldStyled from '../../../components/Other/TextFieldStyled';
import AuthAlert from '../../../components/AuthLayout/AuthAlert';
import FormBoxStyled from '../../../components/Forms/FormBoxStyled';
import AuthButtonStyled from '../../../components/AuthLayout/AuthButtonStyled';
import { ROUTES } from '../../../libs/constants';
import CustomModal from '../../Other/CustomModal';
import ResetPassword from './ResetPassword';

const ForgotPassword: React.FC = () => {
  const dispatch = useAppDispatch();
  const userLang = useAppSelector(store => store.app.userLang);
  const [forgotPassword, { data, error, isFetching, originalArgs }] = authApi.useLazyForgotPasswordQuery();
  const [errorText, setErrorText] = React.useState<string>();
  const [email, setEmail] = React.useState('');
  const [modalState, setModalState] = React.useState(false);

  const forgotPasswordHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    forgotPassword(email);
  };

  React.useEffect(() => {
    if (isFetching == true) {
      setErrorText(undefined);
      return;
    }

    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(String(lang.get(userLang)?.wrongEmail));
          break;
        default:
          setErrorText(makeErrorText(error, userLang));
          break;
      }
    } else {
      if (data) {
        setModalState(true);
      }
    }
  }, [data, error, isFetching, dispatch, userLang]);

  return (
    <React.Fragment>
      <FormBoxStyled onSubmit={forgotPasswordHandler}>
        {errorText && <AuthAlert severity="error" text={errorText} />}
        <TextFieldStyled
          required
          name="email"
          type="email"
          label={lang.get(userLang)?.email}
          value={email}
          onChange={event => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <AuthButtonStyled disabled={isFetching}>
          {isFetching ? lang.get(userLang)?.loading : lang.get(userLang)?.confirm}
        </AuthButtonStyled>
        <AuthLinkStyled href={ROUTES.auth.signUp}>
          {lang.get(userLang)?.signUpText}
        </AuthLinkStyled>
        <AuthLinkStyled href={ROUTES.auth.signIn}>
          {lang.get(userLang)?.signInText}
        </AuthLinkStyled>
      </FormBoxStyled>
      <CustomModal
        open={modalState}
        onClose={() => setModalState(false)}
        title={lang.get(userLang)?.resetPassword}
      >
        <ResetPassword
          email={originalArgs || ''}
          callback={() => setModalState(false)}
        />
      </CustomModal>
    </React.Fragment>
  );
};
export default ForgotPassword;
