// nuxt/components/Forms/Auth/ResetPassword.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormAlert from '../FormAlert.vue'
import FormTextInput from '../FormTextInput.vue'
import FormPasswordInput from '../FormPasswordInput.vue'
import FormButton from '../FormButton.vue'
import { useAuthStore } from '~/stores/auth'

const props = defineProps<{
  email: string
}>()
const emits = defineEmits(['close'])

const { t } = useI18n()
const code = ref('')
const codeIsValid = (value: string) => value.length > 0 || `${t('codeFromEmail')} (${props.email})`
const password = ref('')
const passwordIsValid = (value: string) => testString(PASSWORD_REGEX, value) || t('passwordValidation')
const authStore = useAuthStore()
const errorMsg = ref<string | null>(null)

function submitHandler() {
  if (codeIsValid(code.value) && passwordIsValid(password.value))
    authStore.resetPassword({ email: props.email, password: password.value, code: code.value })
}

watch(
  () => authStore.resetPasswordError,
  () => {
    switch (authStore.resetPasswordError?.status) {
      case 404:
        errorMsg.value = t('wrongEmailOrCode')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(authStore.resetPasswordError?.message)
    }
  },
)

watch(
  () => authStore.resetPasswordData,
  () => {
    if (authStore.resetPasswordData)
      emits('close')
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <FormAlert v-if="errorMsg" :title="$t('error')" :text="errorMsg" type="error" />
    <FormTextInput
      v-model:model-value="code" required name="code" :label="$t('code')"
      :hint="`${$t('codeFromEmail')} (${email})`" :rules="[codeIsValid]"
    />
    <FormPasswordInput
      v-model:model-value="password" required name="password"
      :label="$t('newPassword')" :rules="[passwordIsValid]" :hint="$t('passwordValidation')"
    />
    <FormButton block type="submit" color="success" :loading="authStore.resetPasswordPending">
      {{ $t('confirm') }}
    </FormButton>
    <FormButton block type="button" color="error" @click="$emit('close')">
      {{ $t('close') }}
    </FormButton>
  </FormBox>
</template>

// next/components/Forms/Auth/ResetPassword.tsx
import React from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/dist/query';
import { useRouter } from 'next/router';

import lang from '../../../lib/lang';
import authApi from '../../../store/api/authApi';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { makeErrorText, testString } from '../../../lib/functions';
import TextFieldStyled from '../../../components/Other/TextFieldStyled';
import AuthAlert from '../../../components/AuthLayout/AuthAlert';
import FormBoxStyled from '../../../components/Forms/FormBoxStyled';
import AuthButtonStyled from '../../../components/AuthLayout/AuthButtonStyled';
import { PASSWORD_REGEX } from '../../../lib/constants';
import { ROUTES } from '../../../lib/constants';

const ResetPassword: React.FC<{
  email: string;
  callback?: () => void;
}> = ({ email, callback }) => {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const userLang = useAppSelector(store => store.app.userLang);
  const [resetPassword, { data, error, isLoading }] = authApi.useLazyResetPasswordQuery();
  const [errorText, setErrorText] = React.useState<string>();
  const [code, setCode] = React.useState('');
  const [password, setPassword] = React.useState('');
  const passwordError = React.useMemo(() => testString(PASSWORD_REGEX, password), [password]);

  const resetPasswordHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event?.preventDefault();
    resetPassword({ email, code, password });
  };

  React.useEffect(() => {
    if (isLoading == true) {
      setErrorText(undefined);
      return;
    }

    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(String(lang.get(userLang)?.wrongEmailOrCode));
          break;
        default:
          setErrorText(makeErrorText(error, userLang));
          break;
      }
    } else {
      if (data) {
        if (callback) {
          callback();
        }
        router.push(ROUTES.auth.signIn);
      }
    }
  }, [
    data, error, isLoading,
    dispatch, userLang, router, callback,
  ]);

  return (
    <FormBoxStyled
      autoComplete="off"
      onSubmit={resetPasswordHandler}
    >
      {errorText && <AuthAlert severity="error" text={errorText} />}
      <TextFieldStyled
        required
        autoComplete="off"
        type="text"
        name="code"
        label={lang.get(userLang)?.code}
        value={code}
        onChange={event => setCode(event.currentTarget.value)}
        helperText={`${lang.get(userLang)?.codeFromEmail} (${email})`}
      />
      <TextFieldStyled
        required
        autoComplete="new-password"
        type="password"
        name="newPassword"
        label={lang.get(userLang)?.newPassword}
        value={password}
        onChange={event => setPassword(event.currentTarget.value)}
        color={passwordError ? 'success' : undefined}
        helperText={lang.get(userLang)?.passwordValidation}
        focused={password.length > 0 || undefined}
      />
      <AuthButtonStyled
        disabled={isLoading || data || !passwordError || code.length == 0}
      >
        {isLoading ? lang.get(userLang)?.loading : lang.get(userLang)?.confirm}
      </AuthButtonStyled>
      <AuthButtonStyled color="error" type="button" onClick={callback}>
        {lang.get(userLang)?.close}
      </AuthButtonStyled>
    </FormBoxStyled>
  );
};
export default ResetPassword;
