// nuxt/components/entities/Forms/User/UpdateUserForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/kit/Form/Form.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormCheckbox from '~/components/shared/kit/Form/FormCheckbox.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import { useMainStore } from '~/store/main/main'
import usersApi from '~/api/users/usersApi'
import type { IUser } from '~/api/users/types'

const { user } = defineProps<{ user: IUser }>()

const { t, locale } = useI18n()
const {
  data: uData,
  error: uError,
  execute: uExecute,
  pending: uPending,
} = usersApi.update()
const {
  data: dData,
  error: dError,
  execute: dExecute,
  pending: dPending,
} = usersApi.delete()
const oldData = ref<IUser>(user)
const newData = ref<IUser>(user)
const emailIsValid = (value: string) => testString(EMAIL_REGEX, value) || t('emailValidation')
const nameIsValid = (value: string) => testString(NAME_REGEX, value) || t('nameValidation')
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.users)
const router = useRouter()

async function submitHandler(event: SubmitEventPromise) {
  const results = await event
  const updatedValues = getUpdatedValues<IUser>(
    oldData.value,
    newData.value,
  )

  if (results.valid && Object.keys(updatedValues).length > 0) {
    uExecute({
      id: user.id,
      fields: updatedValues,
    })
  }
}

watch(
  uPending,
  () => {
    if (uPending.value) return

    if (uError.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(uError.value, locale.value) })

    if (uData.value)
      mainStore.addAlert({ type: 'success', text: t('success') })
  },
)

watch(
  dPending,
  () => {
    if (dPending.value) return

    if (dError.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(dError.value, locale.value) })

    if (dData.value) {
      mainStore.addAlert({ type: 'success', text: t('success') })
      router.push(ROUTES.panel.users)
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormField
:hint="$t('emailValidation')" :label="$t('email')" :model-value="newData.email" name="email" required
      :rules="[emailIsValid]" type="email" @update:model-value="newData = { ...newData, email: $event }" />
    <FormField
:hint="$t('nameValidation')" :label="$t('name')" :model-value="newData.name" name="name" required
      :rules="[nameIsValid]" @update:model-value="newData = { ...newData, name: $event }" />
    <FormCheckbox
:label="$t('enabled')" :model-value="newData.enabled" name="enabled"
      @update:model-value="newData = { ...newData, enabled: $event }" />
    <FormButton
color="success" :disabled="!rights.updating || !!dPending || !!dData" :loading="uPending"
      prepand-icon="mdi-content-save" type="submit">
      {{ $t('update') }}
    </FormButton>
    <FormButton
color="error" :disabled="!rights.deleting || user.roles?.some((role) => role.admin)"
      :loading="dPending || !!dData" prepand-icon="mdi-delete" type="button" @click="dExecute(user.id)">
      {{ $t('delete') }}
    </FormButton>
  </Form>
</template>

// next/src/entities/Forms/Users/UpdateUserForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import SaveIcon from '@mui/icons-material/Save';
import DeleteIcon from '@mui/icons-material/Delete';
import { useRouter } from 'next/navigation';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormButton from '@/shared/kit/Form/FormButton';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import useRights from '@/shared/hooks/useRights';
import FormCheckbox from '@/shared/kit/Form/FormCheckbox';
import { useAppDispatch } from '@/shared/store/hooks';
import usersApi from '@/shared/api/users/usersApi';
import { getUpdatedValues, makeErrorText } from '@/shared/lib/utils';
import { addAlert } from '@/shared/store/main/main';
import { IUser } from '@/shared/api/users/types';

const UpdateUserForm: FC<{ data: IUser }> = ({ data }) => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const lang = useLang();
  const t = useT();
  const [update, updateReq] = usersApi.useUpdateMutation();
  const [destroy, deleteReq] = usersApi.useDeleteMutation();
  const [oldData, setOldData] = useState<IUser>(data);
  const [newData, setNewData] = useState<IUser>(data);
  const rights = useRights(ROUTES.api.users);

  const formHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const updatedValues = getUpdatedValues<Partial<IUser>>(oldData, newData);

    if (Object.keys(updatedValues).length == 0) {
      dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
    } else {
      update({ id: data.id, fields: updatedValues });
    }
  };

  useEffect(() => {
    if (updateReq.data) {
      dispatch(addAlert({ type: 'success', text: d[lang.current].success }));
      setOldData((prev) => ({ ...prev, ...updateReq.originalArgs?.fields }));
    }
  }, [updateReq.data, updateReq.originalArgs, dispatch, lang]);

  useEffect(() => {
    if (updateReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(updateReq.error, lang.current),
        })
      );
    }
  }, [updateReq.error, dispatch, lang]);

  useEffect(() => {
    if (deleteReq.data) {
      dispatch(addAlert({ type: 'success', text: d[lang.current].success }));
      router.push(ROUTES.panel.users);
    }
  }, [deleteReq.data, dispatch, router, lang]);

  useEffect(() => {
    if (deleteReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(deleteReq.error, lang.current),
        })
      );
    }
  }, [deleteReq.error, dispatch, lang]);

  return (
    <Form onSubmit={formHandler}>
      <FormField
        required
        name="email"
        type="email"
        label={t.email}
        value={newData.email}
        onChange={(event) =>
          setNewData({ ...newData, email: event.currentTarget.value })
        }
      />
      <FormField
        required
        name="name"
        type="text"
        label={t.name}
        value={newData.name}
        onChange={(event) =>
          setNewData({ ...newData, name: event.currentTarget.value })
        }
      />
      <FormCheckbox
        labelProps={{ label: t.enabled }}
        name="enabled"
        value="enabled"
        checked={newData.enabled}
        onChange={() => setNewData({ ...newData, enabled: !newData.enabled })}
      />
      <FormButton
        type="submit"
        color="success"
        startIcon={<SaveIcon />}
        disabled={!rights.updating || deleteReq.isLoading || deleteReq.data}
        loading={updateReq.isLoading}
      >
        {t.update}
      </FormButton>
      <FormButton
        color="error"
        startIcon={<DeleteIcon />}
        onClick={() => destroy(data.id)}
        disabled={!rights.deleting || data.roles?.some((role) => role.admin)}
        loading={deleteReq.isLoading || deleteReq.data}
      >
        {t.delete}
      </FormButton>
    </Form>
  );
};
export default UpdateUserForm;
