// apps/frontend/panel-react/src/features/resources/ResourceCreate.tsx
import { FC, useEffect } from "react";

import useRights from "@/shared/hooks/useRights";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import { getErrorText, ROUTES } from "@ap/shared/dist/libs";
import ResourceForm from "@/entities/resource/ResourceForm";
import { IResource } from "@ap/shared/dist/types";
import resourcesApi from "@/entities/resource/api";

const ResourceCreate: FC<{ onCreate?: (data: IResource) => void }> = ({
  onCreate,
}) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const [create, createReq] = resourcesApi.useCreateMutation();
  const rights = useRights(ROUTES.api.resources);

  useEffect(() => {
    if (createReq.data) {
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
      onCreate?.(createReq.data);
    }
  }, [createReq.data, dispatch, onCreate, tRef]);

  useEffect(() => {
    if (createReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(createReq.error, lRef.current),
        })
      );
    }
  }, [createReq.error, dispatch, lRef]);

  return (
    <ResourceForm
      onCreate={(fields) => create(fields)}
      createDisabled={!rights.creating}
      createLoading={createReq.isLoading || Boolean(createReq.data)}
    />
  );
};
export default ResourceCreate;

// apps/frontend/panel-vue/components/features/resources/ResourceCreate.vue
<script setup lang="ts">
import resourcesApi from '~/components/entities/resource/resourcesApi'

const emit = defineEmits<{
  create: [value: IResource]
}>()

const { t, locale } = useI18n()
const newData = ref<TResourceCreate>({
  name: '',
  path: '',
  description: '',
  enabled: false,
})
const { data, error, execute, status } = resourcesApi.create(newData)
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.resources)

watch(data, () => {
  if (data.value) {
    mainStore.addAlert({ type: 'success', text: t('success') })
    emit('create', data.value)
  }
})

watch(error, () => {
  if (error.value) {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
  }
})
</script>

<template>
  <ResourceForm
    create-show
    :create-disabled="!rights.creating"
    :create-loading="status === 'pending' || Boolean(data)"
    @create="(fields) => {
      newData = fields
      execute()
    }"
  />
</template>
