// nuxt/pages/roles/index.vue
<script setup lang="ts">
import rolesApi from '~/api/roles/rolesApi'
import RolesList from '~/components/features/Roles/RolesList.vue'

definePageMeta({
  middleware: ['auth'],
  layout: 'panel',
  name: 'roles',
  title: 'roles',
  description: 'roles',
})

const router = useRouter()
const route = useRoute()
const page = ref(Number(route.query.page) || 1)
const quantity = ref(Number(route.query.quantity) || 25)
const { data, execute } = rolesApi.getList(ROUTES.api.roles)
if (import.meta.server)
  await execute({ reqPage: page.value, reqLimit: quantity.value, reqCount: true })

watch(
  page,
  () => {
    router.push({ query: { ...route.query, page: page.value } })
  },
)

watch(
  quantity,
  () => {
    router.push({ query: { ...route.query, quantity: quantity.value } })
  },
)
</script>

<template>
  <RolesList v-model:page="page" v-model:quantity="quantity" :count="data?.count" :rows="data?.rows" />
</template>

// next/src/app/(panel)/roles/page.tsx
import { FC } from 'react';
import { Metadata } from 'next/types';

import rolesService from '@/shared/api/roles/rolesService';
import RolesPage from '@/views/Panel/Roles/RolesPage';
import { IAppPage } from '@/app/types';
import { getT } from '@ap/shared';

export const generateMetadata = async (): Promise<Metadata> => {
  const t = getT();
  return {
    title: t.roles,
    description: t.roles,
  };
};

const Page: FC<IAppPage> = async (props) => {
  const t = getT();
  const page = Number(props.searchParams.page) || 1;
  const quantity = Number(props.searchParams.quantity) || 25;
  const { data } = await rolesService.getList({
    reqPage: page,
    reqLimit: quantity,
    reqCount: true,
  });

  return <RolesPage data={data} h1={t.roles} />;
};
export default Page;
