// apps/frontend/panel-react/src/features/Profile_tmp/ChangeEmailRequestForm.tsx
import { FC, useCallback, useEffect, useMemo, useState } from "react";

import FormBase from "@/shared/ui/form/FormBase";
import FormField from "@/shared/ui/form/FormField";
import FormButton from "@/shared/ui/form/FormButton";
import CustomModal from "@/shared/ui/modal/CustomModal";
import useRights from "@/shared/hooks/useRights";
import { useAppDispatch, useAppSelector } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import ChangeEmailConfirmForm from "./ChangeEmailConfirmForm";
import useTranslate from "@/shared/hooks/useTranslate";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import {
  EMAIL_REGEX,
  getErrorText,
  ROUTES,
  testString,
} from "@ap/shared/dist/libs";
import profileApi from "@/entities/profile/api";

const ChangeEmailRequestForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const t = useTranslate();
  const [confirmModal, setConfirmModal] = useState(false);
  const [changeEmailRequest, { isSuccess, error, isLoading }] =
    profileApi.useChangeEmailRequestMutation();
  const rights = useRights(ROUTES.api.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const [email, setEmail] = useState(profile?.email || "");
  const emailIsValid = useMemo(() => testString(EMAIL_REGEX, email), [email]);
  const onClose = useCallback(() => setConfirmModal(false), []);

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (emailIsValid) {
      if (email === profile?.email) {
        dispatch(addAlert({ type: "warning", text: t.nothingToUpdate }));
      } else {
        changeEmailRequest({ newEmail: email });
      }
    } else {
      dispatch(addAlert({ type: "warning", text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (isSuccess) {
      setConfirmModal(true);
    }
  }, [isSuccess]);

  return (
    <>
      <FormBase onSubmit={submitHandler}>
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          helperText={t.emailValidation}
          color={emailIsValid ? "success" : "error"}
          error={!emailIsValid && email.length > 0}
          disabled={isLoading}
        />
        <FormButton
          type="submit"
          color="success"
          disabled={!rights.updating}
          loading={isLoading}
        >
          {t.change}
        </FormButton>
      </FormBase>
      <CustomModal open={confirmModal} title={t.changeEmail} onClose={onClose}>
        <ChangeEmailConfirmForm email={email} onClose={onClose} />
      </CustomModal>
    </>
  );
};
export default ChangeEmailRequestForm;

// apps/frontend/panel-vue/components/features/profile/ChangeEmailRequestForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import profileApi from '~/components/entities/profile/profileApi'

const { t, locale } = useI18n()
const mainStore = useMainStore()
const email = ref(mainStore.profile?.email || '')
const emailIsValid = (value: string) =>
  value.length > 0 || t('emailValidationI18N')
const { status, error, execute } = profileApi.changeEmailRequest({ newEmail: email })
const confirmModal = ref(false)
const rights = useRights(ROUTES.api.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  if (email.value === mainStore.profile?.email) {
    mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
  else {
    execute()
  }
}

watch(error, () => {
  if (!error.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    confirmModal.value = true
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormField
      v-model="email"
      :hint="$t('emailValidationI18N')"
      :label="$t('email')"
      name="email"
      required
      :rules="[emailIsValid]"
      type="email"
      :disabled="status === 'pending'"
    />
    <FormButton
      color="success"
      :disabled="!rights.updating"
      :loading="status === 'pending'"
      type="submit"
    >
      {{ $t('change') }}
    </FormButton>
    <CustomModal
      v-model="confirmModal"
      :title="$t('resetPassword')"
    >
      <ChangeEmailConfirmForm
        :email="email"
        @close="confirmModal = false"
      />
    </CustomModal>
  </FormBase>
</template>
