// apps/frontend/panel-react/src/features/Profile_tmp/UpdatePasswordForm.tsx
import { FC, FormEvent, useEffect, useMemo, useState } from "react";

import FormBase from "@/shared/ui/form/FormBase";
import FormButton from "@/shared/ui/form/FormButton";
import useRights from "@/shared/hooks/useRights";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import FormPassword from "@/shared/ui/form/FormPassword";
import useTranslate from "@/shared/hooks/useTranslate";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import {
  getErrorText,
  PASSWORD_REGEX,
  ROUTES,
  testString,
} from "@ap/shared/dist/libs";
import profileApi from "@/entities/profile/api";

const UpdatePasswordForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [update, { isSuccess, isLoading, error }] =
    profileApi.useUpdatePasswordMutation();
  const rights = useRights(ROUTES.api.profile);
  const [oldPassword, setOldPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, newPassword),
    [newPassword]
  );

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (passwordIsValid) {
      if (oldPassword === newPassword) {
        dispatch(addAlert({ type: "warning", text: t.nothingToUpdate }));
      } else {
        update({ oldPassword, newPassword });
      }
    } else {
      dispatch(addAlert({ type: "warning", text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (isSuccess) {
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
    }
  }, [isSuccess, dispatch, tRef]);

  return (
    <FormBase onSubmit={submitHandler}>
      <FormPassword
        name="old-password"
        label={t.oldPassword}
        value={oldPassword}
        onChange={(event) => setOldPassword(event.target.value)}
      />
      <FormPassword
        required
        name="new-password"
        label={t.newPassword}
        value={newPassword}
        onChange={(event) => setNewPassword(event.target.value)}
        helperText={t.passwordValidation}
        color={passwordIsValid ? "success" : "error"}
        error={!passwordIsValid && newPassword.length > 0}
      />
      <FormButton
        type="submit"
        color="success"
        disabled={!rights.updating}
        loading={isLoading}
      >
        {t.update}
      </FormButton>
    </FormBase>
  );
};
export default UpdatePasswordForm;

// apps/frontend/panel-vue/components/features/profile/UpdatePasswordForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import profileApi from '~/components/entities/profile/profileApi'

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.profile)
const mainStore = useMainStore()
const oldPassword = ref('')
const newPassword = ref('')
const passwordIsValid = (value: string) =>
  testString(PASSWORD_REGEX, value) || t('passwordValidation')
const { status, error, execute } = profileApi.updatePassword({
  oldPassword,
  newPassword,
})

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  if (oldPassword.value === newPassword.value) {
    mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
  else {
    execute()
  }
}

watch(error, () => {
  if (!error.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormPassword
      v-model="oldPassword"
      :label="$t('oldPassword')"
      name="old-password"
    />
    <FormPassword
      v-model="newPassword"
      :hint="$t('passwordValidation')"
      :label="$t('newPassword')"
      name="new-password"
      required
      :rules="[passwordIsValid]"
    />
    <FormButton
      color="success"
      :disabled="!rights.updating"
      :loading="status === 'pending'"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBase>
</template>
