// apps/frontend/panel-react/src/features/Profile/UpdateProfileForm.tsx
import { FC, FormEvent, useEffect, useMemo, useRef, useState } from "react";

import FormBase from "@/shared/ui/Form/FormBase";
import FormField from "@/shared/ui/Form/FormField";
import FormButton from "@/shared/ui/Form/FormButton";
import useRights from "@/shared/hooks/useRights";
import { useAppDispatch, useAppSelector } from "@/app/store/hooks";
import { addAlert, setProfile } from "@/app/store/main/main";
import useTranslate from "@/shared/hooks/useTranslate";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import {
  getErrorText,
  getUpdatedValues,
  NAME_REGEX,
  ROUTES,
  testString,
} from "@ap/shared/dist/libs";
import { IUser } from "@ap/shared/dist/types";
import profileApi from "@/entities/profile/api";

const UpdateProfileForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [update, { isSuccess, isLoading, error }] =
    profileApi.useUpdateProfileMutation();
  const rights = useRights(ROUTES.api.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const profileRef = useRef(profile);
  const [newData, setNewData] = useState(profile);
  const nameIsValid = useMemo(
    () => newData?.name && testString(NAME_REGEX, newData.name),
    [newData]
  );

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (profile && newData && nameIsValid) {
      const updatedValues = getUpdatedValues<IUser>(profile, newData);

      if (Object.keys(updatedValues).length === 0) {
        dispatch(addAlert({ type: "warning", text: t.nothingToUpdate }));
      } else {
        update(updatedValues);
      }
    } else {
      dispatch(addAlert({ type: "warning", text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (profileRef.current) {
      profileRef.current = { ...profileRef.current, ...newData };
    }
  }, [newData]);

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (isSuccess) {
      dispatch(setProfile(profileRef.current));
      dispatch(addAlert({ type: "success", text: tRef.current.success }));
    }
  }, [isSuccess, dispatch, tRef]);

  return (
    <FormBase onSubmit={submitHandler}>
      {profile?.googleId && (
        <FormField
          name="googleId"
          label={t.googleId}
          value={profile.googleId}
          disabled
        />
      )}
      <FormField
        required
        name="name"
        label={t.name}
        value={newData?.name ?? ""}
        onChange={(event) =>
          newData && setNewData({ ...newData, name: event.target.value })
        }
        helperText={t.nameValidation}
        color={nameIsValid ? "success" : "error"}
        error={!nameIsValid && (newData?.name ?? "").length > 0}
      />
      <FormButton
        type="submit"
        color="success"
        disabled={!rights.updating}
        loading={isLoading}
      >
        {t.update}
      </FormButton>
    </FormBase>
  );
};
export default UpdateProfileForm;

// apps/frontend/panel-vue/components/features/profile_tmp/UpdateProfileForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import profileApi from '~/components/entities/profile/profileApi'

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.profile)
const mainStore = useMainStore()
const newData = ref(mainStore.profile)
const updatedValues = ref<TUserUpdate>({})
const nameIsValid = (value = '') =>
  testString(NAME_REGEX, value) || t('nameValidation')
const { status, error, execute } = profileApi.updateProfile(updatedValues)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  if (mainStore.profile && newData.value) {
    updatedValues.value = getUpdatedValues<IUser>(
      mainStore.profile,
      newData.value,
    )

    if (Object.keys(updatedValues.value).length > 0) {
      execute()
    }
    else {
      mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
    }
  }
}

watch(error, () => {
  if (!error.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    if (mainStore.profile) {
      mainStore.setProfile({ ...mainStore.profile, ...newData.value })
    }

    mainStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormField
      v-if="mainStore.profile?.googleId"
      disabled
      :label="$t('googleId')"
      :model-value="mainStore.profile.googleId"
      name="googleId"
    />
    <FormField
      :label="$t('name')"
      :model-value="newData?.name ?? ''"
      name="name"
      required
      :rules="[nameIsValid]"
      @update:model-value="newData && (newData = { ...newData, name: $event ?? '' })"
    />
    <FormButton
      color="success"
      :disabled="!rights.updating"
      :loading="status === 'pending'"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBase>
</template>
