// apps/frontend/panel-react/src/features/Profile/ChangeEmailRequestForm.tsx
import { FC, useCallback, useEffect, useMemo, useState } from 'react';

import FormBase from '@/shared/ui/Form/FormBase';
import FormField from '@/shared/ui/Form/FormField';
import FormButton from '@/shared/ui/Form/FormButton';
import CustomModal from '@/shared/ui/CustomModal/CustomModal';
import profileApi from '@/shared/api/profile/profileApi';
import useRights from '@/shared/hooks/useRights';
import { useAppDispatch, useAppSelector } from '@/shared/store/hooks';
import { addAlert } from '@/shared/store/main/main';
import ChangeEmailConfirmForm from './ChangeEmailConfirmForm';
import { EMAIL_REGEX, getErrorText, ROUTES, testString } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const ChangeEmailRequestForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const t = useTranslate();
  const [confirmModal, setConfirmModal] = useState(false);
  const [changeEmailRequest, { isSuccess, error, isLoading }] =
    profileApi.useChangeEmailRequestMutation();
  const rights = useRights(ROUTES.api.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const [email, setEmail] = useState(profile?.email || '');
  const emailIsValid = useMemo(() => testString(EMAIL_REGEX, email), [email]);
  const onClose = useCallback(() => setConfirmModal(false), []);

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (emailIsValid) {
      if (email === profile?.email) {
        dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
      } else {
        changeEmailRequest({ newEmail: email });
      }
    } else {
      dispatch(addAlert({ type: 'warning', text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (isSuccess) {
      setConfirmModal(true);
    }
  }, [isSuccess]);

  return (
    <>
      <FormBase onSubmit={submitHandler}>
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          helperText={t.emailValidation}
          color={emailIsValid ? 'success' : 'error'}
          error={!emailIsValid && email.length > 0}
          disabled={isLoading}
        />
        <FormButton
          type="submit"
          color="success"
          disabled={!rights.updating}
          loading={isLoading}
        >
          {t.change}
        </FormButton>
      </FormBase>
      <CustomModal open={confirmModal} title={t.changeEmail} onClose={onClose}>
        <ChangeEmailConfirmForm
          email={email}
          onClose={onClose}
        />
      </CustomModal>
    </>
  );
};
export default ChangeEmailRequestForm;

// nuxt/components/features/Profile/ChangeEmailRequestForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import CustomModal from '~/components/shared/ui/CustomModal/CustomModal.vue'
import ChangeEmailConfirmForm from '~/components/features/Profile/ChangeEmailConfirmForm.vue'
import profileApi from '~/api/profile/profileApi'
import { useMainStore } from '~/store/main/main'

const { t, locale } = useI18n()
const mainStore = useMainStore()
const email = ref(mainStore.profile?.email || '')
const emailIsValid = (value: string) => value.length > 0 || t('emailValidation')
const { data, error, execute, pending, args } = profileApi.changeEmailRequest()
const confirmModal = ref(false)
const rights = useRights(ROUTES.api.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid) {
    if (email.value === mainStore.profile?.email)
      mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
    else
      execute({newEmail: email.value})
  }
}

watch(
  error,
  () => {
    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })
  },
)

watch(
  data,
  () => {
    if (data.value)
      confirmModal.value = true
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormField
v-model="email" :hint="$t('emailValidation')" :label="$t('email')" name="email" required
      :rules="[emailIsValid]" type="email" />
    <FormButton color="success" :disabled="!rights.updating" :loading="pending" type="submit">
      {{ $t('change') }}
    </FormButton>
    <CustomModal v-model="confirmModal" :title="$t('resetPassword')">
      <ChangeEmailConfirmForm :email="args?.newEmail || ''" @close="confirmModal = false" />
    </CustomModal>
  </Form>
</template>
