// next/src/features/Profile/ProfileSessions.tsx
'use client';

import { FC, useEffect, useState } from 'react';
import Skeleton from '@mui/material/Skeleton';

import SessionForm from '@/features/Profile/SessionForm';
import { makeErrorText } from '@/shared/lib/utils';
import { addAlert } from '@/shared/store/main/main';
import { useAppDispatch } from '@/shared/store/hooks';
import useLang from '@/shared/hooks/useLang';
import profileApi from '@/shared/api/profile/profileApi';
import { ISession } from '@/shared/api/profile/types';

const ProfileSessions: FC = () => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const { data, isLoading, error } = profileApi.useGetSessionsQuery();
  const [sessions, setSessions] = useState<ISession[]>();

  useEffect(() => {
    setSessions(
      data &&
        Array.from(data).sort((a, b) => (!a.current && b.current ? 1 : -1))
    );
  }, [data]);

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(error, lang.current),
        })
      );
    }
  }, [dispatch, error, lang]);

  return (
    <>
      {isLoading && (
        <Skeleton variant="rounded" width="100%" height={56} sx={{ mb: 1 }} />
      )}
      {sessions?.map((session) => (
        <SessionForm
          key={session.id}
          session={session}
          onDelete={() =>
            setSessions(sessions.filter((item) => item.id !== session.id))
          }
        />
      ))}
    </>
  );
};
export default ProfileSessions;

// nuxt/components/features/Profile/ProfileSessions.vue
<script setup lang="ts">
import SessionForm from '~/components/features/Profile/SessionForm.vue'
import { useMainStore } from '~/store/main/main'
import profileApi from '~/api/profile/profileApi'
import type { ISession } from '~/api/profile/types'

const { locale } = useI18n()
const { data, error, execute, pending } = profileApi.getSessions()
const mainStore = useMainStore()
const sessions = ref<ISession[] | null>(null)

watch(
  data,
  () => {
    sessions.value = data.value &&
      Array.from(data.value).sort((a, b) => (!a.current && b.current ? 1 : -1))
  },
)

watch(
  error,
  () => {
    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })
  },
)

execute()
</script>

<template>
  <v-skeleton-loader v-if="pending" height="68" />
  <template v-else>
    <SessionForm
v-for="session of sessions" :key="session.id" :session="session"
      @delete="sessions = sessions?.filter((item) => item.id !== session.id) || null" />
  </template>
</template>
