// next/src/features/Profile/UpdatePasswordForm.tsx
import { FC, FormEvent, useEffect, useMemo, useState } from 'react';

import Form from '@/shared/ui/Form/Form';
import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import { useAppDispatch } from '@/shared/store/hooks';
import { addAlert } from '@/shared/store/main/main';
import FormPassword from '@/shared/ui/Form/FormPassword';
import profileApi from '@/shared/api/profile/profileApi';
import { getErrorText, PASSWORD_REGEX, ROUTES, testString } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const UpdatePasswordForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [update, { data, isLoading, error }] =
    profileApi.useUpdatePasswordMutation();
  const rights = useRights(ROUTES.api.profile);
  const [oldPassword, setOldPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, newPassword),
    [newPassword]
  );

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (passwordIsValid) {
      if (oldPassword === newPassword) {
        dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
      } else {
        update({ oldPassword, newPassword });
      }
    } else {
      dispatch(addAlert({ type: 'warning', text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (data) {
      dispatch(addAlert({ type: 'success', text: tRef.current.success }));
    }
  }, [data, dispatch, tRef]);

  return (
    <Form onSubmit={submitHandler}>
      <FormPassword
        name="old-password"
        label={t.oldPassword}
        value={oldPassword}
        onChange={(event) => setOldPassword(event.currentTarget.value)}
      />
      <FormPassword
        required
        name="new-password"
        label={t.newPassword}
        value={newPassword}
        onChange={(event) => setNewPassword(event.currentTarget.value)}
        helperText={t.passwordValidation}
        color={passwordIsValid ? 'success' : 'error'}
        error={!passwordIsValid && newPassword.length > 0}
      />
      <FormButton
        type="submit"
        color="success"
        disabled={!rights.updating}
        loading={isLoading}
      >
        {t.update}
      </FormButton>
    </Form>
  );
};
export default UpdatePasswordForm;

// nuxt/components/features/Profile/UpdatePasswordForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormPassword from '~/components/shared/ui/Form/FormPassword.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import { useMainStore } from '~/store/main/main'
import profileApi from '~/api/profile/profileApi'

const { t, locale } = useI18n()
const mainStore = useMainStore()
const { data, error, execute, pending } = profileApi.updatePassword()
const oldPassword = ref('')
const newPassword = ref('')
const passwordIsValid = (value: string) =>
  testString(PASSWORD_REGEX, value) || t('passwordValidation')
const rights = useRights(ROUTES.api.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid) {
    if (oldPassword.value === newPassword.value)
      mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
    else
      execute({
        oldPassword: oldPassword.value,
        newPassword: newPassword.value,
      })
  }
}

watch(error, () => {
  if (error.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
})

watch(data, () => {
  if (data.value) mainStore.addAlert({ type: 'success', text: t('success') })
})
</script>

<template>
  <Form @submit="submitHandler">
    <FormPassword
      v-model="oldPassword"
      :label="$t('newPassword')"
      name="old-password"
    />
    <FormPassword
      v-model="newPassword"
      :hint="$t('passwordValidation')"
      :label="$t('oldPassword')"
      name="new-password"
      required
      :rules="[passwordIsValid]"
    />
    <FormButton
      color="success"
      :disabled="!rights.updating"
      :loading="pending"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
  </Form>
</template>
