// next/src/features/Profile/UpdateProfileForm.tsx
import { FC, FormEvent, useEffect, useMemo, useRef, useState } from 'react';

import Form from '@/shared/ui/Form/Form';
import FormField from '@/shared/ui/Form/FormField';
import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import { useAppDispatch, useAppSelector } from '@/shared/store/hooks';
import { addAlert, setProfile } from '@/shared/store/main/main';
import profileApi from '@/shared/api/profile/profileApi';
import {
  getErrorText,
  getUpdatedValues,
  IUser,
  NAME_REGEX,
  ROUTES,
  testString,
} from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';
import useTranslateRef from '@/shared/hooks/useTranslateRef';

const UpdateProfileForm: FC = () => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [update, { data, isLoading, error }] =
    profileApi.useUpdateProfileMutation();
  const rights = useRights(ROUTES.api.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const newProfile = useRef(profile);
  const [newData, setNewData] = useState(
    (() => {
      const { email, ...fields } = profile || ({} as Partial<IUser>);
      return fields;
    })()
  );
  const nameIsValid = useMemo(
    () => newData.name && testString(NAME_REGEX, newData.name),
    [newData]
  );

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (profile && nameIsValid) {
      const updatedValues = getUpdatedValues<IUser>(profile, newData);

      if (Object.keys(updatedValues).length == 0) {
        dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
      } else {
        update(updatedValues);
      }
    } else {
      dispatch(addAlert({ type: 'warning', text: t.unknownError }));
    }
  };

  useEffect(() => {
    if (newProfile.current) {
      newProfile.current = { ...newProfile.current, ...newData };
    }
  }, [newData]);

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(error, lRef.current),
        })
      );
    }
  }, [dispatch, error, lRef]);

  useEffect(() => {
    if (data) {
      dispatch(setProfile(newProfile.current));
      dispatch(addAlert({ type: 'success', text: tRef.current.success }));
    }
  }, [data, dispatch, tRef]);

  return (
    <Form onSubmit={submitHandler}>
      {profile?.googleId && (
        <FormField
          name="googleId"
          label={t.googleId}
          value={profile.googleId}
          disabled
        />
      )}
      <FormField
        required
        name="name"
        label={t.name}
        value={newData?.name || ''}
        onChange={(event) =>
          newData && setNewData({ ...newData, name: event.currentTarget.value })
        }
        helperText={t.nameValidation}
        color={nameIsValid ? 'success' : 'error'}
        error={!nameIsValid && (newData?.name || '').length > 0}
      />
      <FormButton
        type="submit"
        color="success"
        disabled={!rights.updating}
        loading={isLoading}
      >
        {t.update}
      </FormButton>
    </Form>
  );
};
export default UpdateProfileForm;

// nuxt/components/features/Profile/UpdateProfileForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import { useMainStore } from '~/store/main/main'
import profileApi from '~/api/profile/profileApi'

const { t, locale } = useI18n()
const mainStore = useMainStore()
const { email, ...profile } = mainStore.profile || ({} as Partial<IUser>)
const newData = ref(profile)
const { data, error, execute, pending } = profileApi.updateProfile()
const nameIsValid = (value = '') =>
  testString(NAME_REGEX, value) || t('nameValidation')
const rights = useRights(ROUTES.api.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (newData.value && mainStore.profile && results.valid) {
    const updatedValues = getUpdatedValues<IUser>(
      mainStore.profile,
      newData.value
    )

    if (Object.keys(updatedValues).length > 0) execute(updatedValues)
    else mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(error, () => {
  if (error.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
})

watch(data, () => {
  if (data.value) {
    if (mainStore.profile)
      mainStore.setProfile({ ...mainStore.profile, ...newData.value })
    mainStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <Form @submit="submitHandler">
    <FormField
v-if="mainStore.profile?.googleId" disabled :label="$t('googleId')"
      :model-value="mainStore.profile.googleId" name="googleId" />
    <FormField
:label="$t('name')" :model-value="newData.name" name="name" required :rules="[nameIsValid]"
      @update:model-value="newData && (newData = { ...newData, name: $event })" />
    <FormButton
color="success" :disabled="!rights.updating" :loading="pending" prepand-icon="mdi-content-save"
      type="submit">
      {{ $t('update') }}
    </FormButton>
  </Form>
</template>
