// apps/frontend/panel-vue/components/features/auth/SignInForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import authApi from '~/components/entities/auth/authApi'

const { t, locale } = useI18n()
const route = useRoute()
const router = useRouter()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0
const password = ref('')
const passwordIsValid = (value: string) => value.length > 0
const rememberMe = ref(false)
const mainStore = useMainStore()
const { data, error, execute, status } = authApi.signIn({
  username: email,
  password,
  rememberMe,
})
const errorText = ref<string | null>(null)
const verifyModal = ref(false)

async function submitHandler(event?: SubmitEventPromise) {
  const results = await event

  if (results && !results.valid) {
    return
  }

  execute()
}

watch(error, () => {
  switch (error.value?.statusCode) {
    case 410:
      errorText.value = t('userDeleted')
      break
    case 403:
      errorText.value = null
      verifyModal.value = true
      break
    case 401:
      errorText.value = t('wrongEmailOrPassword')
      break
    case undefined:
      errorText.value = null
      break
    default:
      errorText.value = getErrorText(error.value, locale.value)
  }
})

watch(data, () => {
  if (data.value) {
    mainStore.setProfile(data.value)
    router.push(
      route.query.return
        ? decodeURIComponent(String(route.query.return))
        : ROUTES.ui.home,
    )
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormAlert
      v-if="errorText"
      :text="errorText"
      type="error"
    />
    <FormField
      v-model="email"
      :label="$t('email')"
      name="email"
      required
      :rules="[emailIsValid]"
      type="email"
      :disabled="status === 'pending' || Boolean(data)"
    />
    <FormPassword
      v-model="password"
      :label="$t('password')"
      name="password"
      required
      :rules="[passwordIsValid]"
      :disabled="status === 'pending' || Boolean(data)"
    />
    <FormCheckbox
      v-model="rememberMe"
      :label="$t('rememberMe')"
      name="rememberMe"
      :disabled="status === 'pending' || Boolean(data)"
    />
    <FormButton
      block
      color="info"
      :loading="status === 'pending' || Boolean(data)"
      type="submit"
    >
      {{ $t('signIn') }}
    </FormButton>
    <FormLink
      :href="ROUTES.ui.signUp"
      :text="$t('signUpText')"
    />
    <FormLink
      :href="ROUTES.ui.forgotPassword"
      :text="$t('forgotPasswordText')"
    />
    <SignInGoogleLink />
  </FormBase>
  <CustomModal
    v-model="verifyModal"
    :title="$t('verification')"
  >
    <VerifyUserForm
      :email="email"
      @close="verifyModal = false"
      @success="submitHandler"
    />
  </CustomModal>
</template>

// apps/frontend/panel-react/src/features/Auth/SignInForm.tsx
import { FC, FormEvent, useEffect, useRef, useState } from "react";
import { FetchBaseQueryError } from "@reduxjs/toolkit/query";
import { useRouter, useSearchParams } from "next/navigation";

import FormBase from "@/shared/ui/Form/FormBase";
import FormField from "@/shared/ui/Form/FormField";
import FormCheckbox from "@/shared/ui/Form/FormCheckbox";
import FormPassword from "@/shared/ui/Form/FormPassword";
import FormButton from "@/shared/ui/Form/FormButton";
import FormLink from "@/shared/ui/Form/FormLink";
import FormAlert from "@/shared/ui/Form/FormAlert";
import CustomModal from "@/shared/ui/CustomModal/CustomModal";
import VerifyUserForm from "./VerifyUserForm";
import { useAppDispatch } from "@/app/store/hooks";
import { setProfile } from "@/app/store/main/main";
import SignInGoogleLink from "./SignInGoogleLink";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import useTranslate from "@/shared/hooks/useTranslate";
import { getErrorText, ROUTES } from "@ap/shared/dist/libs";
import authApi from "@/entities/auth/api";

const SignInForm: FC = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [rememberMe, setRememberMe] = useState(false);
  const [verifyModal, setVerifyModal] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signIn, { data, error, isFetching }] = authApi.useLazySignInQuery();
  const timeout = useRef<NodeJS.Timeout>(undefined);

  const submitHandler = (event?: FormEvent<HTMLFormElement>) => {
    event?.preventDefault();

    if (email && password) {
      signIn({ username: email, password, rememberMe });
    }
  };

  useEffect(() => {
    if (isFetching) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 410:
          setErrorText(tRef.current.userDeleted);
          break;
        case 403:
          setVerifyModal(true);
          break;
        case 401:
          setErrorText(tRef.current.wrongEmailOrPassword);
          break;
        default:
          setErrorText(getErrorText(error, lRef.current));
          break;
      }
    }
  }, [error, tRef, lRef]);

  useEffect(() => {
    if (data) {
      dispatch(setProfile(data));
      router.push(
        decodeURIComponent(searchParams.get("return") || ROUTES.ui.home)
      );
    }
  }, [data, dispatch, router, searchParams]);

  useEffect(() => {
    return () => {
      clearTimeout(timeout.current);
    };
  }, []);

  return (
    <>
      <FormBase onSubmit={submitHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          autoFocus
          disabled={isFetching || Boolean(data)}
        />
        <FormPassword
          required
          name="password"
          label={t.password}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          disabled={isFetching || Boolean(data)}
        />
        <FormCheckbox
          labelProps={{ label: t.rememberMe }}
          name="remember"
          value="remember"
          checked={rememberMe}
          onChange={() => setRememberMe(!rememberMe)}
          disabled={isFetching || Boolean(data)}
        />
        <FormButton
          type="submit"
          fullWidth
          loading={isFetching || Boolean(data)}
        >
          {t.signIn}
        </FormButton>
        <FormLink href={ROUTES.ui.signUp} mui={{ align: "center" }}>
          {t.signUpText}
        </FormLink>
        <FormLink href={ROUTES.ui.forgotPassword} mui={{ align: "center" }}>
          {t.forgotPasswordText}
        </FormLink>
        <SignInGoogleLink />
      </FormBase>
      <CustomModal
        open={verifyModal}
        title={t.verification}
        onClose={() => setVerifyModal(false)}
      >
        <VerifyUserForm
          email={email}
          onClose={() => setVerifyModal(false)}
          onSuccess={() => (timeout.current = setTimeout(submitHandler, 1000))}
        />
      </CustomModal>
    </>
  );
};
export default SignInForm;
