// apps/frontend/panel-vue/components/features/Auth_tmp/SignUpForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import authApi from '~/components/entities/auth/authApi'

const { t, locale } = useI18n()
const name = ref('')
const nameIsValid = (value: string) =>
  testString(NAME_REGEX, value) || t('nameValidation')
const email = ref('')
const emailIsValid = (value: string) =>
  testString(EMAIL_REGEX, value) || t('emailValidationI18N')
const password = ref('')
const passwordIsValid = (value: string) =>
  testString(PASSWORD_REGEX, value) || t('passwordValidation')
const { data, error, execute, status } = authApi.signUp({ name, email, password })
const errorText = ref<string | null>(null)
const successModal = ref(false)
const router = useRouter()

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  execute()
}

function successHandler() {
  successModal.value = false
  router.push(ROUTES.ui.signIn)
}

watch(error, () => {
  switch (error.value?.statusCode) {
    case 409:
      errorText.value = t('userAlreadyExist')
      break
    case undefined:
      errorText.value = null
      break
    default:
      errorText.value = getErrorText(error.value, locale.value)
  }
})

watch(data, () => {
  if (data.value) {
    successModal.value = true
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormAlert
      v-if="errorText"
      :text="errorText"
      type="error"
    />
    <FormField
      v-model="name"
      :hint="$t('nameValidation')"
      :label="$t('name')"
      name="name"
      required
      :rules="[nameIsValid]"
    />
    <FormField
      v-model="email"
      :hint="$t('emailValidationI18N')"
      :label="$t('email')"
      name="email"
      required
      :rules="[emailIsValid]"
      type="email"
    />
    <FormPassword
      v-model="password"
      :hint="$t('passwordValidation')"
      :label="$t('password')"
      name="password"
      required
      :rules="[passwordIsValid]"
    />
    <FormButton
      block
      color="success"
      :loading="status === 'pending'"
      type="submit"
    >
      {{ $t('signUp') }}
    </FormButton>
    <FormLink
      :href="ROUTES.ui.signIn"
      :text="$t('signInText')"
    />
    <FormLink
      :href="ROUTES.ui.forgotPassword"
      :text="$t('forgotPasswordText')"
    />
    <CustomModal
      v-model="successModal"
      :title="$t('registration')"
    >
      <SignUpSuccessForm
        :email="email"
        @close="successHandler"
      />
    </CustomModal>
  </FormBase>
</template>

// apps/frontend/panel-react/src/features/Auth/SignUpForm.tsx
import { FC, useEffect, useMemo, useState } from "react";
import { FetchBaseQueryError } from "@reduxjs/toolkit/query";
import { useRouter } from "next/navigation";

import FormBase from "@/shared/ui/Form/FormBase";
import FormField from "@/shared/ui/Form/FormField";
import FormPassword from "@/shared/ui/Form/FormPassword";
import FormButton from "@/shared/ui/Form/FormButton";
import FormLink from "@/shared/ui/Form/FormLink";
import FormAlert from "@/shared/ui/Form/FormAlert";
import CustomModal from "@/shared/ui/CustomModal/CustomModal";
import SignUpSuccessForm from "./SignUpSuccessForm";
import useTranslate from "@/shared/hooks/useTranslate";
import useTranslateRef from "@/shared/hooks/useTranslateRef";
import useLanguageRef from "@/shared/hooks/useLanguageRef";
import {
  EMAIL_REGEX,
  getErrorText,
  NAME_REGEX,
  PASSWORD_REGEX,
  ROUTES,
  testString,
} from "@ap/shared/dist/libs";
import authApi from "@/entities/auth/api";

const SignUpForm: FC = () => {
  const router = useRouter();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [name, setName] = useState("");
  const nameIsValid = useMemo(() => testString(NAME_REGEX, name), [name]);
  const [email, setEmail] = useState("");
  const emailIsValid = useMemo(() => testString(EMAIL_REGEX, email), [email]);
  const [password, setPassword] = useState("");
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, password),
    [password]
  );
  const [successModal, setSuccessModal] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signUp, { data, error, isLoading }] = authApi.useLazySignUpQuery();

  const submitHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (nameIsValid && emailIsValid && passwordIsValid) {
      signUp({
        name: name.trim(),
        email: email.trim(),
        password,
      });
    }
  };

  const successHandler = () => {
    setSuccessModal(false);
    router.push(ROUTES.ui.signIn);
  };

  useEffect(() => {
    if (isLoading) {
      setErrorText(null);
    }
  }, [isLoading]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 409:
          setErrorText(tRef.current.userAlreadyExist);
          break;
        default:
          setErrorText(getErrorText(error, lRef.current));
          break;
      }
    }
  }, [error, tRef, lRef]);

  useEffect(() => {
    if (data) {
      setSuccessModal(true);
    }
  }, [data]);

  return (
    <>
      <FormBase onSubmit={submitHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="name"
          label={t.name}
          value={name}
          onChange={(event) => setName(event.target.value)}
          helperText={t.nameValidation}
          color={nameIsValid ? "success" : "error"}
          error={!nameIsValid && name.length > 0}
          autoFocus
        />
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          helperText={t.emailValidation}
          color={emailIsValid ? "success" : "error"}
          error={!emailIsValid && email.length > 0}
        />
        <FormPassword
          required
          name="password"
          label={t.password}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          helperText={t.passwordValidation}
          color={passwordIsValid ? "success" : "error"}
          error={!passwordIsValid && password.length > 0}
        />
        <FormButton type="submit" fullWidth loading={isLoading}>
          {t.signUp}
        </FormButton>
        <FormLink href={ROUTES.ui.signIn} mui={{ align: "center" }}>
          {t.signInText}
        </FormLink>
        <FormLink href={ROUTES.ui.forgotPassword} mui={{ align: "center" }}>
          {t.forgotPasswordText}
        </FormLink>
      </FormBase>
      <CustomModal
        open={successModal}
        title={t.registration}
        onClose={() => setSuccessModal(false)}
      >
        <SignUpSuccessForm onClose={successHandler} />
      </CustomModal>
    </>
  );
};
export default SignUpForm;
