// nuxt/components/Forms/User/UpdateUserRoles.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormCheckbox from '../FormCheckbox.vue'
import FormButton from '../FormButton.vue'
import { useMainStore } from '~/stores/main'
import { useUsersStore } from '~/stores/users'
import type { IRole, IUser, IUsersRoles } from '~/utils/types'

const { user, roles } = defineProps<{ user: IUser; roles: IRole[] }>()

const updatedRoles = ref(user.roles?.map(role => role.UsersRoles) || [])
const { t } = useI18n()
const usersStore = useUsersStore()
const mainStore = useMainStore()
const rights = useRights(ROUTES.api.users)

function submitHandler() {
  usersStore.updateRoles({
    id: user.id,
    fields: updatedRoles.value,
  })
}

function setRoles(newRole: IUsersRoles) {
  let find = false

  const filtered = updatedRoles.value.filter((value) => {
    if (
      newRole.userId === value?.userId
      && newRole.roleId === value?.roleId
    ) {
      find = true
      return false
    }
    else {
      return true
    }
  })

  if (!find)
    filtered.push(newRole)

  updatedRoles.value = filtered
}

watch(
  () => usersStore.updateRolesPending,
  () => {
    if (usersStore.updateRolesPending === true)
      return
    if (usersStore.updateRolesError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(usersStore.updateRolesError) })
    if (usersStore.updateRolesData)
      mainStore.addAlert({ type: 'success', text: t('success') })
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <div class="d-flex flex-row">
      <span v-for="role of roles" :key="`userRole.${role.id}`" class="mr-6">
        <FormCheckbox
          :model-value="updatedRoles.some(value => value?.roleId === role.id)"
          :name="`${role.name}.${role.id}`"
          :label="role.name"
          @update:model-value="setRoles({ roleId: role.id, userId: user.id })"
        />
      </span>
    </div>
    <FormButton
      type="submit" color="success" prepand-icon="mdi-content-save"
      :loading="usersStore.updateRolesPending" :disabled="!rights.updating"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBox>
</template>

// next/components/Forms/User/UpdateUserRoles.tsx
import React from 'react';
import { Typography } from '@mui/material';

import usersApi from '../../../store/api/usersApi';
import { makeErrorText } from '../../../lib/functions';
import { IRole, IUser, IUsersRoles } from '../../../lib/types';
import { useAppDispatch } from '../../../store/hooks';
import { addAlert } from '../../../store/slices/appSlice';
import FormActions from '../FormActions';
import FormBoxStyled from '../FormBoxStyled';
import FormCheckbox from '../FormCheckbox';
import { ROUTES } from '../../../lib/constants';
import useRights from '../../../hooks/useRights';
import dictionary from '../../../locales/dictionary';
import useLang from '../../../hooks/useLang';
import useT from 'hooks/useT';

const UpdateUserRoles: React.FC<{
  user: IUser;
  roles: IRole[];
}> = ({ user, roles }) => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const t = useT();
  const [update, updateReq] = usersApi.useUpdateRolesMutation();
  const [updatedRoles, setUpdatedRoles] = React.useState(
    user.roles?.map((value) => value.UsersRoles) || []
  );
  const rights = useRights(ROUTES.api.users);

  const updateHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    update({
      id: user.id,
      fields: updatedRoles,
    });
  };

  const updateRoles = (newRole: IUsersRoles) => {
    let find = false;

    const filtered = updatedRoles.filter((value) => {
      if (newRole.userId == value?.userId && newRole.roleId == value?.roleId) {
        find = true;
        return false;
      } else {
        return true;
      }
    });

    if (!find) {
      filtered.push(newRole);
    }

    setUpdatedRoles(filtered);
  };

  React.useEffect(() => {
    if (updateReq.isLoading) {
      return;
    }
    if (updateReq.data === false || updateReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(updateReq.error, lang.current),
        })
      );
    }
    if (updateReq.data) {
      dispatch(
        addAlert({ type: 'success', text: dictionary[lang.current].success })
      );
    }
  }, [updateReq.data, updateReq.error, updateReq.isLoading, dispatch, lang]);

  return (
    <FormBoxStyled onSubmit={updateHandler}>
      <Typography component="h2" variant="h5" sx={{ my: 1.5, lineHeight: 1 }}>
        {t.roles}
      </Typography>
      {roles.map((role) => (
        <FormCheckbox
          key={`roleRow.${role.id}`}
          label={role.name}
          name="role[]"
          value="allowed"
          checked={updatedRoles.some((value) => value?.roleId == role.id)}
          onChange={() => updateRoles({ roleId: role.id, userId: user.id })}
        />
      ))}
      {roles && (
        <FormActions
          update={{
            loading: updateReq.isLoading,
            disabled: !rights.updating,
          }}
        />
      )}
    </FormBoxStyled>
  );
};
export default UpdateUserRoles;
