// nuxt/components/entities/Forms/Auth/ForgotForm.vue
<script setup lang="ts">
import Form from '~/components/shared/kit/Form/Form.vue'
import FormAlert from '~/components/shared/kit/Form/FormAlert.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import FormLink from '~/components/shared/kit/Form/FormLink.vue'
import CustomModal from '~/components/shared/kit/CustomModal/CustomModal.vue'
import ResetForm from '~/components/entities/Forms/Auth/ResetForm.vue'
import { useAuthStore } from '~/stores/auth/auth'

const { t, locale } = useI18n()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0 || t('emailValidation')
const authStore = useAuthStore()
const errorMsg = ref<string | null>(null)
const resetModal = ref(false)
const router = useRouter()

function formHandler() {
  if (emailIsValid(email.value) === true)
    authStore.forgotPassword(email.value)
}

watch(
  () => authStore.forgotPasswordError,
  () => {
    switch (authStore.forgotPasswordError?.status) {
      case 404:
        errorMsg.value = t('wrongEmail')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(authStore.forgotPasswordError?.message, locale.value)
    }
  },
)

watch(
  () => authStore.forgotPasswordData,
  () => {
    if (authStore.forgotPasswordData)
      resetModal.value = true
  },
)

watch(
  () => authStore.resetPasswordData,
  () => {
    if (authStore.resetPasswordData)
      router.push(ROUTES.auth.signIn)
  },
)
</script>

<template>
  <Form @submit="formHandler">
    <FormAlert v-if="errorMsg" :text="errorMsg" type="error" />
    <FormField v-model:model-value="email" required name="email" type="text" :label="$t('email')"
      :rules="[emailIsValid]" :hint="$t('emailValidation')" />
    <FormButton block type="submit" color="success" :loading="authStore.forgotPasswordPending">
      {{ $t('confirm') }}
    </FormButton>
    <FormLink :href="ROUTES.auth.signIn" :text="$t('signInText')" />
    <FormLink :href="ROUTES.auth.signUp" :text="$t('signUpText')" />
    <CustomModal v-model="resetModal" :title="$t('resetPassword')">
      <ResetForm :email="email" @close="resetModal = false" />
    </CustomModal>
  </Form>
</template>

// next/src/entities/Forms/Auth/ForgotForm.tsx
import { FC, useEffect, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormButton from '@/shared/kit/Form/FormButton';
import FormLink from '@/shared/kit/Form/FormLink';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/shared/kit/Form/FormAlert';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import CustomModal from '@/shared/kit/CustomModal/CustomModal';
import ResetForm from './ResetForm';
import authApi from '@/shared/api/auth/authApi';
import { makeErrorText } from '@/shared/lib/utils';

const ForgotForm: FC = () => {
  const t = useT();
  const lang = useLang();
  const [email, setEmail] = useState('');
  const [modalState, setModalState] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [forgotPassword, { data, error, isFetching, originalArgs }] =
    authApi.useLazyForgotPasswordQuery();

  const formHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (email) {
      forgotPassword(email);
    }
  };

  useEffect(() => {
    if (isFetching === true) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(d[lang.current].wrongEmail);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data) {
      setModalState(true);
    }
  }, [data]);

  return (
    <>
      <Form onSubmit={formHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <FormButton type="submit" fullWidth disabled={isFetching}>
          {t.confirm}
        </FormButton>
        <FormLink href={ROUTES.auth.signIn} mui={{ align: 'center' }}>
          {t.signInText}
        </FormLink>
        <FormLink href={ROUTES.auth.signUp} mui={{ align: 'center' }}>
          {t.signUpText}
        </FormLink>
      </Form>
      <CustomModal
        open={modalState}
        title={t.resetPassword}
        onClose={() => setModalState(false)}
      >
        <ResetForm
          email={originalArgs || ''}
          callback={() => setModalState(false)}
        />
      </CustomModal>
    </>
  );
};
export default ForgotForm;
