// nuxt/components/entities/Forms/Auth/ResetForm.vue
<script setup lang="ts">
import Form from '~/components/shared/kit/Form/Form.vue'
import FormAlert from '~/components/shared/kit/Form/FormAlert.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormPassword from '~/components/shared/kit/Form/FormPassword.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import { useAuthStore } from '~/stores/auth/auth'

const props = defineProps<{
  email: string
}>()
const emits = defineEmits(['close'])

const { t, locale } = useI18n()
const code = ref('')
const codeIsValid = (value: string) => value.length > 0 || `${t('codeFromEmail')} (${props.email})`
const password = ref('')
const passwordIsValid = (value: string) => testString(PASSWORD_REGEX, value) || t('passwordValidation')
const authStore = useAuthStore()
const errorMsg = ref<string | null>(null)

function formHandler() {
  if (codeIsValid(code.value) === true && passwordIsValid(password.value) === true)
    authStore.resetPassword({ email: props.email, password: password.value, code: code.value })
}

watch(
  () => authStore.resetPasswordError,
  () => {
    switch (authStore.resetPasswordError?.status) {
      case 404:
        errorMsg.value = t('wrongEmailOrCode')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(authStore.resetPasswordError?.message, locale.value)
    }
  },
)

watch(
  () => authStore.resetPasswordData,
  () => {
    if (authStore.resetPasswordData)
      emits('close')
  },
)
</script>

<template>
  <Form @submit="formHandler">
    <FormAlert v-if="errorMsg" :text="errorMsg" type="error" />
    <FormField v-model:model-value="code" required name="code" :label="$t('code')"
      :hint="`${$t('codeFromEmail')} (${email})`" :rules="[codeIsValid]" />
    <FormPassword v-model:model-value="password" required name="password" :label="$t('newPassword')"
      :rules="[passwordIsValid]" :hint="$t('passwordValidation')" />
    <FormButton block type="submit" color="success" :loading="authStore.resetPasswordPending">
      {{ $t('confirm') }}
    </FormButton>
    <FormButton block type="button" color="error" @click="$emit('close')">
      {{ $t('close') }}
    </FormButton>
  </Form>
</template>

// next/src/entities/Forms/Auth/ResetForm.tsx
import { FC, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

import Form from '@/kit/Form/Form';
import FormButton from '@/kit/Form/FormButton';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/kit/Form/FormAlert';
import { PASSWORD_REGEX, ROUTES } from '@/shared/lib/constants';
import FormField from '@/kit/Form/FormField';
import FormPassword from '@/kit/Form/FormPassword';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import authApi from '@/shared/api/auth/authApi';
import { makeErrorText, testString } from '@/shared/lib/utils';

const ResetForm: FC<{
  email: string;
  callback?: () => void;
}> = ({ email, callback }) => {
  const router = useRouter();
  const t = useT();
  const lang = useLang();
  const [resetPassword, { data, error, isLoading }] =
    authApi.useLazyResetPasswordQuery();
  const [errorText, setErrorText] = useState<string | null>(null);
  const [code, setCode] = useState('');
  const [password, setPassword] = useState('');
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, password),
    [password]
  );

  const formHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event?.preventDefault();
    if (email && code && passwordIsValid) {
      resetPassword({ email, code, password });
    }
  };

  useEffect(() => {
    if (isLoading === true) {
      setErrorText(null);
    }
  }, [isLoading]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(d[lang.current].wrongEmailOrCode);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data) {
      if (callback) {
        callback();
      }
      router.push(ROUTES.auth.signIn);
    }
  }, [data, callback, router]);

  return (
    <Form onSubmit={formHandler}>
      {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
      <FormField
        required
        autoComplete="off"
        type="text"
        name="code"
        label={t.code}
        value={code}
        onChange={(event) => setCode(event.currentTarget.value)}
        helperText={`${t.codeFromEmail} (${email})`}
      />
      <FormPassword
        required
        autoComplete="new-password"
        name="newPassword"
        label={t.newPassword}
        value={password}
        onChange={(event) => setPassword(event.currentTarget.value)}
        helperText={t.passwordValidation}
        color={passwordIsValid ? 'success' : 'error'}
        error={!passwordIsValid && password.length > 0}
      />
      <FormButton type="submit" fullWidth disabled={isLoading}>
        {t.confirm}
      </FormButton>
      <FormButton fullWidth color="error" onClick={callback}>
        {t.close}
      </FormButton>
    </Form>
  );
};
export default ResetForm;
