// nuxt/components/entities/Forms/Auth/SessionForm.vue
<script setup lang="ts">
import UAParser from 'ua-parser-js'

import Form from '~/components/shared/kit/Form/Form.vue'
import { useMainStore } from '~/store/main/main'
import authApi from '~/api/auth/authApi'
import type { ISession } from '~/api/auth/types'

const { session } = defineProps<{ session: ISession }>()
const emits = defineEmits(['delete'])

const { t, locale } = useI18n()
const mainStore = useMainStore()
const { data, error, execute, pending } = authApi.deleteSessions()
const rights = useRights(ROUTES.api.auth.profile)
const userAgent = ref(new UAParser(session.userAgent).getResult())

async function submitHandler() {
  execute([session.id])
}

watch(
  pending,
  () => {
    if (pending.value) return

    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })

    if (data.value) {
      emits('delete')
      mainStore.addAlert({ type: 'success', text: t('success') })
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <v-card class="mb-1 d-flex flex-row">
      <v-card-text class="d-flex flex-row align-center">
        <template v-if="userAgent.device.vendor">
          <v-icon class="mr-1" icon="mdi-cellphone" />
          <span class="text-body-2">
            {{ userAgent.device.vendor }}{{ ' ' }}
            {{ userAgent.device.model }}
            {{ ',' }}&nbsp;
          </span>
        </template>
        <template v-else>
          <v-icon class="mr-1" icon="mdi-laptop" />
          <span class="text-body-2">
            {{ userAgent.os.name }} {{ userAgent.os.version }}
            {{ ',' }}&nbsp;
          </span>
        </template>
        <span class="text-body-2">
          {{ userAgent.browser.name }} {{ userAgent.browser.version }}
          {{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-80">
          {{ session.ip }}
          {{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-60 mr-2">
          {{ makeDateString(session.updatedAt) }}
        </span>
        <v-chip v-if="session.current" color="success" variant="outlined">{{ $t('current') }}</v-chip>
      </v-card-text>
      <v-card-actions>
        <v-btn
color="error" :disabled="!rights.updating || pending || !!data" icon="mdi-delete" type="submit"
          variant="text" />
      </v-card-actions>
    </v-card>
  </Form>
</template>

// next/src/entities/Forms/Auth/SessionForm.tsx
import { FC, FormEvent, useEffect, useRef } from 'react';
import UAParser from 'ua-parser-js';
import DeleteIcon from '@mui/icons-material/Delete';
import ComputerIcon from '@mui/icons-material/Computer';
import SmartphoneIcon from '@mui/icons-material/Smartphone';
import {
  Card,
  CardActions,
  CardContent,
  Chip,
  IconButton,
  styled,
  Typography,
} from '@mui/material';

import Form from '@/shared/kit/Form/Form';
import useT from '@/shared/hooks/useT';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import authApi from '@/shared/api/auth/authApi';
import { useAppDispatch } from '@/shared/store/hooks';
import { makeDateString, makeErrorText } from '@/shared/lib/utils';
import { addAlert } from '@/shared/store/main/main';
import { ISession } from '@/shared/api/auth/types';
import theme from '@/shared/lib/theme';
import { ROUTES } from '@/shared/lib/constants';
import useRights from '@/shared/hooks/useRights';

const SessionForm: FC<{ session: ISession; onDelete?: () => void }> = ({
  session,
  onDelete,
}) => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const t = useT();
  const rights = useRights(ROUTES.api.auth.profile);
  const userAgent = useRef(new UAParser(session.userAgent).getResult());
  const [remove, { data, isLoading, error }] =
    authApi.useDeleteSessionsMutation();

  const formHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    remove([session.id]);
  };

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(error, lang.current),
        })
      );
    }
  }, [dispatch, error, lang]);

  useEffect(() => {
    if (data) {
      dispatch(addAlert({ type: 'success', text: d[lang.current].success }));
      onDelete?.();
    }
  }, [data, dispatch, lang, onDelete]);

  return (
    <Form onSubmit={formHandler}>
      <Session>
        <SessionContent>
          {userAgent.current.device.vendor ? (
            <>
              <SmartphoneIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.device.vendor}{' '}
                {userAgent.current.device.model}
                {','}&nbsp;
              </Typography>
            </>
          ) : (
            <>
              <ComputerIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.current.os.name} {userAgent.current.os.version}
                {','}&nbsp;
              </Typography>
            </>
          )}
          <Typography component="span" variant="body2">
            {userAgent.current.browser.name} {userAgent.current.browser.version}
            {','}&nbsp;
          </Typography>
          <Typography component="span" variant="body2" sx={{ opacity: 0.8 }}>
            {session.ip}
            {','}&nbsp;
          </Typography>
          <Typography
            component="span"
            variant="body2"
            sx={{ mr: 1, opacity: 0.6 }}
          >
            {makeDateString(session.updatedAt)}
          </Typography>
          {session.current && (
            <Chip
              label={t.current}
              color="success"
              variant="outlined"
              size="small"
            />
          )}
        </SessionContent>
        <CardActions sx={{ pr: 2 }}>
          <IconButton
            edge="end"
            color="error"
            aria-label="sign out"
            title={t.signOut}
            disabled={!rights.updating || isLoading || data}
            type="submit"
          >
            <DeleteIcon />
          </IconButton>
        </CardActions>
      </Session>
    </Form>
  );
};
export default SessionForm;

const Session = styled(Card)`
  display: flex;
  flex-direction: row;
  margin-bottom: ${theme.spacing(1)};
`;

const SessionContent = styled(CardContent)`
  flex-grow: 1;
  display: flex;
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
`;
