// nuxt/components/features/Auth/SignUpForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/ui/Form/Form.vue'
import FormAlert from '~/components/shared/ui/Form/FormAlert.vue'
import FormField from '~/components/shared/ui/Form/FormField.vue'
import FormPassword from '~/components/shared/ui/Form/FormPassword.vue'
import FormButton from '~/components/shared/ui/Form/FormButton.vue'
import FormLink from '~/components/shared/ui/Form/FormLink.vue'
import CustomModal from '~/components/shared/ui/CustomModal/CustomModal.vue'
import SignUpSuccessForm from '~/components/features/Auth/SignUpSuccessForm.vue'
import authApi from '~/api/auth/authApi'

const { t, locale } = useI18n()
const name = ref('')
const nameIsValid = (value: string) => testString(NAME_REGEX, value) || t('nameValidation')
const email = ref('')
const emailIsValid = (value: string) => testString(EMAIL_REGEX, value) || t('emailValidation')
const password = ref('')
const passwordIsValid = (value: string) => testString(PASSWORD_REGEX, value) || t('passwordValidation')
const { data, error, execute, pending } = authApi.signUp()
const errorText = ref<string | null>(null)
const successModal = ref(false)
const router = useRouter()

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid)
    execute({ name: name.value, email: email.value, password: password.value })
}

function successHandler() {
  successModal.value = false
  router.push(ROUTES.ui.signIn)
}

watch(
  error,
  () => {
    if (error.value)
      switch (error.value?.status) {
        case 409:
          errorText.value = t('userAlreadyExist')
          break
        case undefined:
          errorText.value = null
          break
        default:
          errorText.value = makeErrorText(error.value, locale.value)
      }
  },
)

watch(
  data,
  () => {
    if (data.value)
      successModal.value = true
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormAlert v-if="errorText" :text="errorText" type="error" />
    <FormField
v-model="name" :hint="$t('nameValidation')" :label="$t('name')" name="name" required
      :rules="[nameIsValid]" />
    <FormField
v-model="email" :hint="$t('emailValidation')" :label="$t('email')" name="email" required
      :rules="[emailIsValid]" type="email" />
    <FormPassword
v-model="password" :hint="$t('passwordValidation')" :label="$t('password')" name="password" required
      :rules="[passwordIsValid]" />
    <FormButton block color="success" :loading="pending" type="submit">
      {{ $t('signUp') }}
    </FormButton>
    <FormLink :href="ROUTES.ui.signIn" :text="$t('signInText')" />
    <FormLink :href="ROUTES.ui.forget" :text="$t('forgotPasswordText')" />
    <CustomModal v-model="successModal" :title="$t('registration')">
      <SignUpSuccessForm :email="email" @close="successHandler" />
    </CustomModal>
  </Form>
</template>

// next/src/entities/Forms/Auth/SignUpForm.tsx
import { FC, useEffect, useMemo, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormPassword from '@/shared/kit/Form/FormPassword';
import FormButton from '@/shared/kit/Form/FormButton';
import FormLink from '@/shared/kit/Form/FormLink';
import {
  EMAIL_REGEX,
  NAME_REGEX,
  PASSWORD_REGEX,
  ROUTES,
} from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/shared/kit/Form/FormAlert';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import CustomModal from '@/shared/kit/CustomModal/CustomModal';
import SignUpSuccessForm from './SignUpSuccessForm';
import { makeErrorText, testString } from '@/shared/lib/utils';
import authApi from '@/shared/api/auth/authApi';

const SignUpForm: FC = () => {
  const t = useT();
  const lang = useLang();
  const [name, setName] = useState('');
  const nameIsValid = useMemo(() => testString(NAME_REGEX, name), [name]);
  const [email, setEmail] = useState('');
  const emailIsValid = useMemo(() => testString(EMAIL_REGEX, email), [email]);
  const [password, setPassword] = useState('');
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, password),
    [password]
  );
  const [modalState, setModalState] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signUp, { data, error, isLoading }] = authApi.useLazySignUpQuery();

  const formHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (nameIsValid && emailIsValid && passwordIsValid) {
      signUp({
        name: name.trim(),
        email: email.trim(),
        password,
      });
    }
  };

  useEffect(() => {
    if (isLoading === true) {
      setErrorText(null);
    }
  }, [isLoading]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 409:
          setErrorText(d[lang.current].userAlreadyExist);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data) {
      setModalState(true);
    }
  }, [data]);

  return (
    <>
      <Form onSubmit={formHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="name"
          type="text"
          label={t.name}
          value={name}
          onChange={(event) => setName(event.currentTarget.value)}
          helperText={t.nameValidation}
          color={nameIsValid ? 'success' : 'error'}
          error={!nameIsValid && name.length > 0}
          autoFocus
        />
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.currentTarget.value)}
          helperText={t.emailValidation}
          color={emailIsValid ? 'success' : 'error'}
          error={!emailIsValid && email.length > 0}
        />
        <FormPassword
          required
          name="password"
          label={t.password}
          value={password}
          onChange={(event) => setPassword(event.currentTarget.value)}
          helperText={t.passwordValidation}
          color={passwordIsValid ? 'success' : 'error'}
          error={!passwordIsValid && password.length > 0}
        />
        <FormButton type="submit" fullWidth loading={isLoading || !!data}>
          {t.signUp}
        </FormButton>
        <FormLink href={ROUTES.auth.signIn} mui={{ align: 'center' }}>
          {t.signInText}
        </FormLink>
        <FormLink href={ROUTES.auth.forget} mui={{ align: 'center' }}>
          {t.forgotPasswordText}
        </FormLink>
      </Form>
      <CustomModal
        open={modalState}
        title={t.registration}
        onClose={() => setModalState(false)}
      >
        <SignUpSuccessForm callback={() => setModalState(false)} />
      </CustomModal>
    </>
  );
};
export default SignUpForm;
