// nuxt/components/entities/Forms/Auth/SignInForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/kit/Form/Form.vue'
import FormAlert from '~/components/shared/kit/Form/FormAlert.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormPassword from '~/components/shared/kit/Form/FormPassword.vue'
import FormCheckbox from '~/components/shared/kit/Form/FormCheckbox.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import FormLink from '~/components/shared/kit/Form/FormLink.vue'
import CustomModal from '~/components/shared/kit/CustomModal/CustomModal.vue'
import VerifyUserForm from '~/components/entities/Forms/Auth/VerifyUserForm.vue'
import { useMainStore } from '~/store/main/main'
import authApi from '~/api/auth/authApi'

const { t, locale } = useI18n()
const route = useRoute()
const router = useRouter()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0
const password = ref('')
const passwordIsValid = (value: string) => value.length > 0
const rememberMe = ref(false)
const mainStore = useMainStore()
const { data, error, execute, pending } = authApi.signIn()
const errorMsg = ref<string | null>(null)
const verifyModal = ref(false)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (results.valid)
    execute({ username: email.value, password: password.value, rememberMe: rememberMe.value })
}

watch(
  error,
  () => {
    switch (error.value?.status) {
      case 410:
        errorMsg.value = t('userDeleted')
        break
      case 403:
        errorMsg.value = null
        verifyModal.value = true
        break
      case 401:
        errorMsg.value = t('wrongEmailOrPassword')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(error.value, locale.value)
    }
  },
)

watch(
  data,
  () => {
    if (data.value)
      mainStore.setProfile(data.value)
  },
)

watch(
  () => mainStore.profile,
  () => {
    if (mainStore.profile)
      router.push(route.query.return ? decodeURIComponent(String(route.query.return)) : ROUTES.panel.home)
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormAlert v-if="errorMsg" :text="errorMsg" type="error" />
    <FormField v-model="email" :label="$t('email')" name="email" required :rules="[emailIsValid]" />
    <FormPassword v-model="password" :label="$t('password')" name="password" required :rules="[passwordIsValid]" />
    <FormCheckbox v-model="rememberMe" :label="$t('rememberMe')" name="rememberMe" />
    <FormButton block color="info" :loading="pending || Boolean(data)" type="submit">
      {{ $t('signIn') }}
    </FormButton>
    <FormLink :href="ROUTES.auth.signUp" :text="$t('signUpText')" />
    <FormLink :href="ROUTES.auth.forget" :text="$t('forgotPasswordText')" />
  </Form>
  <CustomModal v-model="verifyModal" :title="$t('verification')">
    <VerifyUserForm :email="email" @close="verifyModal = false" />
  </CustomModal>
</template>

// next/src/entities/Forms/Auth/SignInForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';
import { useRouter, useSearchParams } from 'next/navigation';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormCheckbox from '@/shared/kit/Form/FormCheckbox';
import FormPassword from '@/shared/kit/Form/FormPassword';
import FormButton from '@/shared/kit/Form/FormButton';
import FormLink from '@/shared/kit/Form/FormLink';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/shared/kit/Form/FormAlert';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import CustomModal from '@/shared/kit/CustomModal/CustomModal';
import VerifyUserForm from './VerifyUserForm';
import { useAppDispatch } from '@/shared/store/hooks';
import authApi from '@/shared/api/auth/authApi';
import { makeErrorText } from '@/shared/lib/utils';
import { setProfile } from '@/shared/store/main/main';

const SignInForm: FC = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const dispatch = useAppDispatch();
  const t = useT();
  const lang = useLang();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);
  const [modalState, setModalState] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [signIn, { data, error, isFetching, originalArgs }] =
    authApi.useLazySignInQuery();

  const formHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (email && password) {
      signIn({ username: email, password, rememberMe });
    }
  };

  useEffect(() => {
    if (isFetching === true) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 410:
          setErrorText(d[lang.current].userDeleted);
          break;
        case 403:
          setModalState(true);
          break;
        case 401:
          setErrorText(d[lang.current].wrongEmailOrPassword);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data) {
      dispatch(setProfile(data));
      router.push(
        decodeURIComponent(searchParams.get('return') || ROUTES.panel.home)
      );
    }
  }, [data, dispatch, router, searchParams]);

  return (
    <>
      <Form onSubmit={formHandler}>
        {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
        <FormField
          required
          name="email"
          type="email"
          label={t.email}
          value={email}
          onChange={(event) => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <FormPassword
          required
          name="password"
          label={t.password}
          value={password}
          onChange={(event) => setPassword(event.currentTarget.value)}
        />
        <FormCheckbox
          labelProps={{ label: t.rememberMe }}
          name="remember"
          value="remember"
          checked={rememberMe}
          onChange={() => setRememberMe(!rememberMe)}
        />
        <FormButton
          type="submit"
          fullWidth
          loading={isFetching || Boolean(data)}
        >
          {t.signIn}
        </FormButton>
        <FormLink href={ROUTES.auth.signUp} mui={{ align: 'center' }}>
          {t.signUpText}
        </FormLink>
        <FormLink href={ROUTES.auth.forget} mui={{ align: 'center' }}>
          {t.forgotPasswordText}
        </FormLink>
      </Form>
      <CustomModal
        open={modalState}
        title={t.verification}
        onClose={() => setModalState(false)}
      >
        <VerifyUserForm
          email={originalArgs?.username || ''}
          callback={() => setModalState(false)}
        />
      </CustomModal>
    </>
  );
};
export default SignInForm;
