// nuxt/components/entities/Forms/Auth/UpdateProfileForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import Form from '~/components/shared/kit/Form/Form.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import { useMainStore } from '~/store/main/main'
import authApi from '~/api/auth/authApi'
import type { IUser } from '~/api/users/types'

const { t, locale } = useI18n()
const mainStore = useMainStore()
const newData = ref(mainStore.profile)
const { data, error, execute, pending } = authApi.updateProfile()
const nameIsValid = (value = '') => testString(NAME_REGEX, value) || t('nameValidation')
const rights = useRights(ROUTES.api.auth.profile)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (newData.value && mainStore.profile && results.valid) {
    const updatedValues = getUpdatedValues<IUser>(
      mainStore.profile,
      newData.value,
    )

    if (Object.keys(updatedValues).length > 0)
      execute(updatedValues)
    else
      mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(
  pending,
  () => {
    if (pending.value) return

    if (error.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(error.value, locale.value) })

    if (data.value) {
      mainStore.setProfile(newData.value)
      mainStore.addAlert({ type: 'success', text: t('success') })
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormField
:label="$t('name')" :model-value="newData?.name" name="name" required :rules="[nameIsValid]"
      @update:model-value="newData && (newData = { ...newData, name: $event })" />
    <FormButton
color="success" :disabled="!rights.updating" :loading="pending" prepand-icon="mdi-content-save"
      type="submit">
      {{ $t('update') }}
    </FormButton>
  </Form>
</template>

// next/src/entities/Forms/Auth/UpdateProfileForm.tsx
import { FC, FormEvent, useEffect, useMemo, useRef, useState } from 'react';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormButton from '@/shared/kit/Form/FormButton';
import { NAME_REGEX, ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import useRights from '@/shared/hooks/useRights';
import authApi from '@/shared/api/auth/authApi';
import { useAppDispatch, useAppSelector } from '@/shared/store/hooks';
import {
  getUpdatedValues,
  makeErrorText,
  testString,
} from '@/shared/lib/utils';
import { addAlert, setProfile } from '@/shared/store/main/main';
import { IUser } from '@/shared/api/users/types';

const UpdateProfileForm: FC = () => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const t = useT();
  const [update, { data, isLoading, error }] =
    authApi.useUpdateProfileMutation();
  const rights = useRights(ROUTES.api.auth.profile);
  const profile = useAppSelector((store) => store.main.profile);
  const newProfile = useRef<IUser | null>(profile);
  const [newData, setNewData] = useState<IUser | null>(profile);
  const nameIsValid = useMemo(
    () => newData && testString(NAME_REGEX, newData.name),
    [newData]
  );

  const formHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (profile && newData && nameIsValid) {
      const updatedValues = getUpdatedValues<IUser>(profile, newData);

      if (Object.keys(updatedValues).length == 0) {
        dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
      } else {
        update(updatedValues);
      }
    } else {
      dispatch(addAlert({ type: 'warning', text: t.unknownError }));
    }
  };

  useEffect(() => {
    newProfile.current = newData;
  }, [newData]);

  useEffect(() => {
    if (error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(error, lang.current),
        })
      );
    }
  }, [dispatch, error, lang]);

  useEffect(() => {
    if (data) {
      dispatch(setProfile(newProfile.current));
      dispatch(addAlert({ type: 'success', text: d[lang.current].success }));
    }
  }, [data, dispatch, lang]);

  return (
    <Form onSubmit={formHandler}>
      <FormField
        required
        name="name"
        type="text"
        label={t.name}
        value={newData?.name || ''}
        onChange={(event) =>
          newData && setNewData({ ...newData, name: event.currentTarget.value })
        }
      />
      <FormButton
        type="submit"
        color="success"
        disabled={!rights.updating}
        loading={isLoading}
      >
        {t.update}
      </FormButton>
    </Form>
  );
};
export default UpdateProfileForm;
