// nuxt/components/entities/Forms/Auth/VerifyForm.vue
<script setup lang="ts">
import Form from '~/components/shared/kit/Form/Form.vue'
import FormAlert from '~/components/shared/kit/Form/FormAlert.vue'
import FormField from '~/components/shared/kit/Form/FormField.vue'
import FormButton from '~/components/shared/kit/Form/FormButton.vue'
import { useAuthStore } from '~/stores/auth/auth'

const props = defineProps<{
  email: string
}>()
const emits = defineEmits(['close'])

const { t, locale } = useI18n()
const code = ref('')
const codeIsValid = (value: string) => value.length > 0 || `${t('codeFromEmail')} (${props.email})`
const authStore = useAuthStore()
const errorMsg = ref<string | null>(null)

function formHandler() {
  if (codeIsValid(code.value) === true)
    authStore.verify({ email: props.email, code: code.value })
}

watch(
  () => authStore.verifyError,
  () => {
    switch (authStore.verifyError?.status) {
      case 404:
        errorMsg.value = t('wrongCode')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(authStore.verifyError?.message, locale.value)
    }
  },
)

watch(
  () => authStore.verifyData,
  () => {
    if (authStore.verifyData)
      emits('close')
  },
)
</script>

<template>
  <Form @submit="formHandler">
    <FormAlert v-if="errorMsg" :text="errorMsg" type="error" />
    <FormField
v-model:model-value="code" required name="code" :label="$t('code')"
      :hint="`${$t('codeFromEmail')} (${email})`" :rules="[codeIsValid]" />
    <FormButton block type="submit" color="success" :loading="authStore.verifyPending">
      {{ $t('confirm') }}
    </FormButton>
    <FormButton block type="button" color="error" @click="$emit('close')">
      {{ $t('close') }}
    </FormButton>
  </Form>
</template>

// next/src/entities/Forms/Auth/VerifyForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';

import Form from '@/shared/kit/Form/Form';
import FormField from '@/shared/kit/Form/FormField';
import FormButton from '@/shared/kit/Form/FormButton';
import useT from '@/shared/hooks/useT';
import FormAlert from '@/shared/kit/Form/FormAlert';
import useLang from '@/shared/hooks/useLang';
import d from '@/shared/locales/dictionary';
import authApi from '@/shared/api/auth/authApi';
import { makeErrorText } from '@/shared/lib/utils';

const VerifyUser: FC<{
  email: string;
  callback?: () => void;
}> = ({ email, callback }) => {
  const t = useT();
  const lang = useLang();
  const [verifyUser, { data, error, isFetching }] =
    authApi.useLazyVerifyUserQuery();
  const [errorText, setErrorText] = useState<string | null>(null);
  const [code, setCode] = useState('');

  const verifyHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    verifyUser({ email, code });
  };

  useEffect(() => {
    if (isFetching === true) {
      setErrorText(null);
    }
  }, [isFetching]);

  useEffect(() => {
    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 404:
          setErrorText(d[lang.current].wrongCode);
          break;
        default:
          setErrorText(makeErrorText(error, lang.current));
          break;
      }
    }
  }, [error, lang]);

  useEffect(() => {
    if (data && callback) {
      callback();
    }
  }, [data, callback]);

  return (
    <Form onSubmit={verifyHandler}>
      {errorText && <FormAlert severity="error">{errorText}</FormAlert>}
      <FormField
        required
        autoComplete="off"
        type="text"
        name="code"
        label={t.code}
        value={code}
        onChange={(event) => setCode(event.currentTarget.value)}
        helperText={`${t.codeFromEmail} (${email})`}
      />
      <FormButton type="submit" fullWidth disabled={isFetching || data}>
        {t.confirm}
      </FormButton>
      <FormButton color="error" onClick={callback} fullWidth>
        {t.close}
      </FormButton>
    </Form>
  );
};
export default VerifyUser;
