// apps/frontend/panel-vue/components/features/Users/UsersList.vue
<script setup lang="ts">
const props = defineProps<{
  rows?: IUser[]
  page?: number
  limit?: number
  count?: number
}>()
defineEmits<{
  'update:page': [value: number]
  'update:limit': [value: number]
}>()

const { locale } = useI18n()
const rights = useRights(ROUTES.api.users)
const mainStore = useMainStore()
const items = ref(props.rows)
const page = ref(props.page || 1)
const limit = ref(props.limit || 25)
const reqCount = ref(false)
const selected = ref<string[]>([])
const {
  data: glData,
  error: glError,
  execute: glExecute,
  status: glStatus,
} = usersApi.getList({ reqPage: page, reqLimit: limit, reqCount })
const {
  error: dError,
  execute: dExecute,
  status: dStatus,
} = usersApi.delete({ items: selected })
const count = computed(
  () => glData.value?.count || props.count || page.value * limit.value,
)

watch(
  () => props.rows,
  () => {
    if (!props.rows) {
      reqCount.value = true
      glExecute()
      reqCount.value = false
    }
  },
  { immediate: true },
)

watch([page, limit], () => {
  glExecute()
})

watch(glData, () => {
  if (glData.value) {
    items.value = glData.value.rows
  }
})

watch(glError, () => {
  if (!glError.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(glError.value, locale.value),
  })
})

watch(dStatus, () => {
  if (dStatus.value === 'success') {
    reqCount.value = true
    glExecute()
    reqCount.value = false
  }
})

watch(dError, () => {
  if (!dError.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(dError.value, locale.value),
  })
})
</script>

<template>
  <div class="mb-3">
    <NuxtLink :href="rights.creating ? ROUTES.ui.newUser : undefined">
      <v-btn
        class="me-2"
        color="info"
        :disabled="!rights.creating"
        prepend-icon="mdi-plus"
        variant="flat"
      >
        {{ $t('create') }}
      </v-btn>
    </NuxtLink>
    <v-btn
      color="error"
      :disabled="!rights.deleting || selected.length === 0"
      :loading="dStatus === 'pending'"
      prepend-icon="mdi-delete"
      variant="flat"
      @click="dExecute()"
    >
      {{ $t('delete') }}
    </v-btn>
  </div>
  <UsersTable
    v-model:page="page"
    v-model:quantity="limit"
    v-model:selected="selected"
    :count="count"
    :loading="dStatus === 'pending' || glStatus === 'pending'"
    :rows="items"
    @update:page="$emit('update:page', $event)"
    @update:quantity="$emit('update:limit', $event)"
  />
</template>

// next/src/features/Users/UsersList.tsx
'use client';

import { FC, useEffect, useMemo, useRef, useState } from 'react';
import DeleteIcon from '@mui/icons-material/Delete';
import AddIcon from '@mui/icons-material/Add';
import { GridPaginationModel } from '@mui/x-data-grid/models';

import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import { IList } from '@/shared/lib/types';
import usersApi from '@/shared/api/users/usersApi';
import UsersTable from '@/entities/Users/UsersTable';
import { useAppDispatch } from '@/shared/store/hooks';
import { addAlert } from '@/shared/store/main/main';
import { getErrorText, IUser, ROUTES } from '@ap/shared';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';

const UsersList: FC<IList<IUser>> = (props) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const t = useTranslate();
  const rights = useRights(ROUTES.api.users);
  const [getList, getListReq] = usersApi.useLazyGetListQuery();
  const [destroy, destroyReq] = usersApi.useDeleteMutation();
  const [selectedRows, setSelectedRows] = useState<string[]>([]);
  const [items, setItems] = useState(props.rows);
  const paginationModel = useRef<GridPaginationModel>({
    page: (props.page || 1) - 1,
    pageSize: props.quantity || 25,
  });
  const count = useMemo(
    () =>
      getListReq.data?.count ||
      props.count ||
      paginationModel.current.page * paginationModel.current.pageSize,
    [props.count, getListReq.data]
  );

  const paginationHandler = (model: GridPaginationModel) => {
    getList({ reqPage: model.page + 1, reqLimit: model.pageSize });
    paginationModel.current = model;
    props.onPageUpdate?.(model.page + 1);
    props.onQuantityUpdate?.(model.pageSize);
  };

  useEffect(() => {
    if (!props.rows) {
      getList({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [props.rows, getList]);

  useEffect(() => {
    if (destroyReq.data) {
      getList({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [destroyReq.data, getList]);

  useEffect(() => {
    if (destroyReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(destroyReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, destroyReq.error, lRef]);

  useEffect(() => {
    if (getListReq.data) {
      setItems(getListReq.data.rows);
    }
  }, [getListReq.data]);

  useEffect(() => {
    if (getListReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(getListReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, getListReq.error, lRef]);

  useEffect(() => {
    if (getListReq.data?.rows) {
      setItems(getListReq.data?.rows);
    }
  }, [getListReq.data]);

  useEffect(() => {
    if (getListReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(getListReq.error, lRef.current),
        })
      );
    }
  }, [dispatch, getListReq.error, lRef]);

  return (
    <>
      <FormButton
        color="primary"
        startIcon={<AddIcon />}
        disabled={!rights.creating}
        href={ROUTES.ui.newUser}
      >
        {t.create}
      </FormButton>
      <FormButton
        color="error"
        startIcon={<DeleteIcon />}
        disabled={
          !rights.deleting || selectedRows.length === 0 || destroyReq.isLoading
        }
        onClick={() => destroy({ items: selectedRows })}
      >
        {t.delete}
      </FormButton>
      <UsersTable
        initialState={{
          pagination: {
            paginationModel: paginationModel.current,
          },
        }}
        rows={items}
        rowCount={count}
        loading={getListReq.isLoading || destroyReq.isLoading}
        onRowSelectionModelChange={(rowSelectionModel) =>
          setSelectedRows(rowSelectionModel as string[])
        }
        onPaginationModelChange={paginationHandler}
      />
    </>
  );
};
export default UsersList;
