// next/components/Forms/Resource/CreateResource.tsx
import React from 'react';
import { useRouter } from 'next/router';

import lang from '../../../lib/lang';
import resourcesApi from '../../../store/api/resourcesApi';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { addAlert } from '../../../store/slices/appSlice';
import FormActions from '../FormActions';
import TextFieldStyled from '../../Other/TextFieldStyled';
import FormBoxStyled from '../FormBoxStyled';
import { makeErrorText } from '../../../lib/functions';
import { ROUTES } from '../../../lib/constants';
import FormCheckbox from '../FormCheckbox';
import useRights from '../../../hooks/useRights';

const CreateResource: React.FC = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const userLang = useAppSelector(store => store.app.userLang);
  const [create, createReq] = resourcesApi.useCreateMutation();
  const [name, setName] = React.useState('');
  const [path, setPath] = React.useState('');
  const [description, setDescription] = React.useState('');
  const [enabled, setEnabled] = React.useState(true);
  const rights = useRights(ROUTES.api.resources);

  const createHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    create({ name, path, description: description || null, enabled });
  };

  React.useEffect(() => {
    if (createReq.isLoading) {
      return;
    }
    if (createReq.error) {
      dispatch(addAlert({ type: 'error', text: makeErrorText(createReq.error, userLang) }));
    }
    if (createReq.data) {
      dispatch(addAlert({ type: 'success', text: lang.get(userLang)?.success }));
      router.push(ROUTES.panel.resource(createReq.data.id));
    }
  }, [
    createReq.data, createReq.error, createReq.isLoading,
    dispatch, userLang, router,
  ]);

  return (
    <FormBoxStyled onSubmit={createHandler}>
      <TextFieldStyled
        required
        name="name"
        type="text"
        label={lang.get(userLang)?.name}
        value={name}
        onChange={event => setName(event.currentTarget.value)}
      />
      <TextFieldStyled
        required
        name="path"
        type="text"
        label={lang.get(userLang)?.path}
        value={path}
        onChange={event => setPath(event.currentTarget.value)}
      />
      <TextFieldStyled
        name="description"
        type="text"
        label={lang.get(userLang)?.description}
        value={description}
        onChange={event => setDescription(event.currentTarget.value)}
      />
      <FormCheckbox
        label={lang.get(userLang)?.enabled}
        name="enabled"
        value="enabled"
        checked={enabled}
        onChange={() => setEnabled(!enabled)}
      />
      <FormActions
        create={{
          loading: createReq.isLoading || Boolean(createReq.data),
          disabled: !rights.creating,
        }}
      />
    </FormBoxStyled>
  );
};
export default CreateResource;

// nuxt/components/Forms/Resource/CreateResource.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormTextInput from '../FormTextInput.vue'
import FormCheckbox from '../FormCheckbox.vue'
import FormButton from '../FormButton.vue'
import { useResourcesStore } from '~/stores/resources'
import { useMainStore } from '~/stores/main'

const { t } = useI18n()
const name = ref('')
const nameIsValid = (value: string) => value.length > 0
const path = ref('')
const pathIsValid = (value: string) => value.length > 0
const description = ref('')
const enabled = ref(true)
const resourcesStore = useResourcesStore()
const mainStore = useMainStore()
const router = useRouter()
const rights = useRights(ROUTES.api.resources)

function submitHandler() {
  if (nameIsValid(name.value) && pathIsValid(path.value))
    resourcesStore.create({ name: name.value, path: path.value, description: description.value || null, enabled: enabled.value })
}

watch(
  () => resourcesStore.createPending,
  () => {
    if (resourcesStore.createPending === true)
      return
    if (resourcesStore.createError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(resourcesStore.createError) })
    if (resourcesStore.createData) {
      mainStore.addAlert({ type: 'success', text: t('success') })
      router.push(ROUTES.panel.resource(resourcesStore.createData.id))
    }
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <FormTextInput v-model:model-value="name" required name="name" :label="$t('name')" :rules="[nameIsValid]" />
    <FormTextInput v-model:model-value="path" required name="path" :label="$t('path')" :rules="[pathIsValid]" />
    <FormTextInput v-model:model-value="description" name="description" :label="$t('description')" />
    <FormCheckbox v-model:model-value="enabled" name="enabled" :label="$t('enabled')" />
    <FormButton type="submit" color="info" prepand-icon="mdi-plus" :loading="resourcesStore.createPending" :disabled="!rights.creating">
      {{ $t('create') }}
    </FormButton>
  </FormBox>
</template>
