// next/src/features/Roles/RolesList.tsx
'use client';

import { FC, useEffect, useMemo, useRef, useState } from 'react';
import DeleteIcon from '@mui/icons-material/Delete';
import AddIcon from '@mui/icons-material/Add';
import { GridPaginationModel } from '@mui/x-data-grid/models';

import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import { ROUTES } from '@/shared/lib/constants';
import useT from '@/shared/hooks/useT';
import { IList } from '@/shared/lib/types';
import { IRole } from '@/shared/api/roles/types';
import RolesTable from '@/entities/Roles/RolesTable';
import rolesApi from '@/shared/api/roles/rolesApi';
import { useAppDispatch } from '@/shared/store/hooks';
import useLang from '@/shared/hooks/useLang';
import { makeErrorText } from '@/shared/lib/utils';
import { addAlert } from '@/shared/store/main/main';

const RolesList: FC<IList<IRole>> = (props) => {
  const dispatch = useAppDispatch();
  const lang = useLang();
  const t = useT();
  const rights = useRights(ROUTES.api.roles);
  const [findAll, findAllReq] = rolesApi.useLazyFindAllQuery();
  const [destroy, destroyReq] = rolesApi.useDeleteMutation();
  const [selectedRows, setSelectedRows] = useState<string[]>([]);
  const [items, setItems] = useState(props.rows);
  const paginationModel = useRef<GridPaginationModel>({
    page: (props.page || 1) - 1,
    pageSize: props.quantity || 25,
  });
  const count = useMemo(
    () =>
      findAllReq.data?.count ||
      props.count ||
      paginationModel.current.page * paginationModel.current.pageSize,
    [props.count, findAllReq.data]
  );

  const paginationHandler = (model: GridPaginationModel) => {
    findAll({ reqPage: model.page + 1, reqLimit: model.pageSize });
    paginationModel.current = model;
    props.onPageUpdate?.(model.page + 1);
    props.onQuantityUpdate?.(model.pageSize);
  };

  useEffect(() => {
    if (!props.rows) {
      findAll({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [props.rows, findAll]);

  useEffect(() => {
    if (destroyReq.data) {
      findAll({
        reqPage: paginationModel.current.page + 1,
        reqLimit: paginationModel.current.pageSize,
      });
    }
  }, [destroyReq.data, findAll]);

  useEffect(() => {
    if (destroyReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(destroyReq.error, lang.current),
        })
      );
    }
  }, [dispatch, destroyReq.error, lang]);

  useEffect(() => {
    if (findAllReq.data) {
      setItems(findAllReq.data.rows);
    }
  }, [findAllReq.data]);

  useEffect(() => {
    if (findAllReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(findAllReq.error, lang.current),
        })
      );
    }
  }, [dispatch, findAllReq.error, lang]);

  useEffect(() => {
    if (findAllReq.data?.rows) {
      setItems(findAllReq.data?.rows);
    }
  }, [findAllReq.data]);

  useEffect(() => {
    if (findAllReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: makeErrorText(findAllReq.error, lang.current),
        })
      );
    }
  }, [dispatch, findAllReq.error, lang]);

  return (
    <>
      <FormButton
        color="primary"
        startIcon={<AddIcon />}
        disabled={!rights.creating}
        href={ROUTES.ui.newRole}
      >
        {t.create}
      </FormButton>
      <FormButton
        color="error"
        startIcon={<DeleteIcon />}
        disabled={
          !rights.deleting || selectedRows.length === 0 || destroyReq.isLoading
        }
        onClick={() => destroy({ items: selectedRows })}
      >
        {t.delete}
      </FormButton>
      <RolesTable
        initialState={{
          pagination: {
            paginationModel: paginationModel.current,
          },
        }}
        rows={items}
        rowCount={count}
        loading={findAllReq.isLoading || destroyReq.isLoading}
        onRowSelectionModelChange={(rowSelectionModel) =>
          setSelectedRows(rowSelectionModel as string[])
        }
        onPaginationModelChange={paginationHandler}
      />
    </>
  );
};
export default RolesList;

// nuxt/components/features/Roles/RolesList.vue
<script setup lang="ts">
import type { IRole } from '~/api/roles/types'
import rolesApi from '~/api/roles/rolesApi'
import RolesTable from '~/components/entities/Role/RolesTable.vue'
import { useMainStore } from '~/store/main/main'

const props = defineProps<{
  rows?: IRole[]
  count?: number
  page?: number
  quantity?: number
}>()
defineEmits<{
  'update:page': [value: number]
  'update:quantity': [value: number]
}>()

const { locale } = useI18n()
const { data: faData, error: faError, execute: faExecute, pending: faPending } = rolesApi.findAll()
const { data: dData, error: dError, execute: dExecute, pending: dPending } = rolesApi.delete()
const page = ref(props.page || 1)
const quantity = ref(props.quantity || 25)
const count = computed(() => faData.value?.count || props.count || page.value * quantity.value)
const items = ref(props.rows)
const rights = useRights(ROUTES.api.roles)
const mainStore = useMainStore()
const selected = ref<string[]>([])

watch(
  () => props.rows,
  () => {
    if (!props.rows) {
      faExecute({ reqPage: page.value, reqLimit: quantity.value, reqCount: true })
    }
  },
  { immediate: true },
)

watch(
  [page, quantity],
  () => {
    faExecute({ reqPage: page.value, reqLimit: quantity.value })
  },
)

watch(
  faData,
  () => {
    if (faData.value)
      items.value = faData.value.rows
  },
)

watch(
  faError,
  () => {
    if (faError.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(faError.value, locale.value) })
  },
)

watch(
  dData,
  () => {
    if (dData.value) {
      faExecute({ reqPage: page.value, reqLimit: quantity.value, reqCount: true })
    }
  },
)

watch(
  dError,
  () => {
    if (dError.value)
      mainStore.addAlert({ type: 'error', text: makeErrorText(dError.value, locale.value) })
  },
)
</script>

<template>
  <div class="mb-3">
    <NuxtLink :href="rights.creating ? ROUTES.ui.newRole : undefined">
      <v-btn class="me-2" color="info" :disabled="!rights.creating" prepend-icon="mdi-plus" variant="flat">
        {{ $t('create') }}
      </v-btn>
    </NuxtLink>
    <v-btn
color="error" :disabled="!rights.deleting || selected.length === 0" :loading="dPending"
      prepend-icon="mdi-delete" variant="flat" @click="dExecute({items: selected})">
      {{ $t('delete') }}
    </v-btn>
  </div>
  <RolesTable
v-model:page="page" v-model:quantity="quantity" v-model:selected="selected" :count="count"
    :loading="dPending || faPending" :rows="items" @update:page="$emit('update:page', $event)"
    @update:quantity="$emit('update:quantity', $event)" />
</template>
