// apps/frontend/panel-react/src/features/Roles/UpdateRoleRightsForm.tsx
import { FC, FormEvent, useEffect, useState } from 'react';
import SaveIcon from '@mui/icons-material/Save';

import FormBase from '@/shared/ui/Form/FormBase';
import FormButton from '@/shared/ui/Form/FormButton';
import useRights from '@/shared/hooks/useRights';
import ResourceRightsFields from '../Resources/ResourceRightsFields';
import { useAppDispatch } from '@/shared/store/hooks';
import rolesApi from '@/shared/api/roles/rolesApi';
import { addAlert } from '@/shared/store/main/main';
import useTranslate from '@/shared/hooks/useTranslate';
import useLanguageRef from '@/shared/hooks/useLanguageRef';
import useTranslateRef from '@/shared/hooks/useTranslateRef';
import { getErrorText, ROUTES } from '@ap/shared/src/libs';
import { IResource, IRights, IRole } from '@ap/shared/src/types';

const UpdateRoleRightsForm: FC<{
  role: IRole;
  resources: IResource[];
}> = ({ role, resources }) => {
  const dispatch = useAppDispatch();
  const lRef = useLanguageRef();
  const tRef = useTranslateRef();
  const t = useTranslate();
  const [update, updateReq] = rolesApi.useUpdateRightsMutation();
  const [updatedRights, setUpdatedRights] = useState(role.rights || []);
  const rights = useRights(ROUTES.api.roles);

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    update({
      id: role.id,
      fields: { items: updatedRights },
    });
  };

  const updateRights = (newRights: IRights) => {
    const filteredRights = updatedRights.filter((value) => {
      if (
        newRights.roleId === value.roleId &&
        newRights.resourceId === value.resourceId
      ) {
        return false;
      } else {
        return true;
      }
    });

    if (
      newRights.creating ||
      newRights.reading ||
      newRights.updating ||
      newRights.deleting
    ) {
      filteredRights.push(newRights);
    }

    setUpdatedRights(filteredRights);
  };

  useEffect(() => {
    if (updateReq.isSuccess) {
      dispatch(addAlert({ type: 'success', text: tRef.current.success }));
    }
  }, [updateReq.isSuccess, dispatch, tRef]);

  useEffect(() => {
    if (updateReq.error) {
      dispatch(
        addAlert({
          type: 'error',
          text: getErrorText(updateReq.error, lRef.current),
        })
      );
    }
  }, [updateReq.error, dispatch, lRef]);

  return (
    <FormBase onSubmit={submitHandler}>
      {resources.map((resource) => (
        <ResourceRightsFields
          key={`ResourceRights.${resource.id}`}
          roleId={role.id}
          resource={resource}
          rights={updatedRights.find(
            (value) => value.resourceId === resource.id
          )}
          setRights={updateRights}
        />
      ))}
      <br />
      <FormButton
        type="submit"
        color="success"
        startIcon={<SaveIcon />}
        disabled={!rights.updating || role.default}
        loading={updateReq.isLoading}
      >
        {t.update}
      </FormButton>
    </FormBase>
  );
};
export default UpdateRoleRightsForm;

// nuxt/components/features/Roles/UpdateRoleRightsForm.vue
<script setup lang="ts">
const { role, resources } = defineProps<{
  role: IRole
  resources: IResource[]
}>()

const { t, locale } = useI18n()
const { status, error, execute } = rolesApi.updateRights()
const mainStore = useMainStore()
const updatedRights = ref<IRights[]>(role.rights || [])
const rights = useRights(ROUTES.api.roles)

function submitHandler() {
  execute({
    id: role.id,
    fields: { items: updatedRights.value },
  })
}

function updateRights(newRights: IRights) {
  const filteredRights = updatedRights.value.filter((value) => {
    if (
      newRights.roleId === value.roleId
      && newRights.resourceId === value.resourceId
    ) {
      return false
    }
    else {
      return true
    }
  })

  if (
    newRights.creating
    || newRights.reading
    || newRights.updating
    || newRights.deleting
  ) {
    filteredRights.push(newRights)
  }

  updatedRights.value = filteredRights
}

watch(error, () => {
  if (error.value)
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
})

watch(status, () => {
  if (status.value === 'success') mainStore.addAlert({ type: 'success', text: t('success') })
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <div class="d-flex flex-row">
      <ResourceRightsFields
        v-for="resource of resources"
        :key="`resourceRights.${resource.id}`"
        :resource="resource"
        :rights="updatedRights.find((value) => value.resourceId === resource.id)"
        :role-id="role.id"
        @update="updateRights"
      />
    </div>
    <FormButton
      color="success"
      :disabled="!rights.updating || role.default"
      :loading="status === 'pending'"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBase>
</template>
