// next/components/Forms/Auth/Authorization.tsx
import { FetchBaseQueryError } from '@reduxjs/toolkit/dist/query';
import { useRouter } from 'next/router';
import React from 'react';

import lang from '../../../libs/lang';
import authApi from '../../../store/api/authApi';
import { setProfile } from '../../../store/slices/appSlice';
import { makeErrorText } from '../../../libs/functions';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import AuthLinkStyled from '../../../components/AuthLayout/AuthLinkStyled';
import TextFieldStyled from '../../../components/Other/TextFieldStyled';
import AuthAlert from '../../../components/AuthLayout/AuthAlert';
import FormCheckbox from '../../../components/Forms/FormCheckbox';
import FormBoxStyled from '../../../components/Forms/FormBoxStyled';
import AuthButtonStyled from '../../../components/AuthLayout/AuthButtonStyled';
import CustomModal from '../../Other/CustomModal';
import VerifyUser from './VerifyUser';
import { ROUTES } from '../../../libs/constants';

const Authorization: React.FC = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const userLang = useAppSelector(store => store.app.userLang);
  const [signIn, { data, error, isFetching, originalArgs }] = authApi.useLazySignInQuery();
  const [errorText, setErrorText] = React.useState<string>();
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState('');
  const [rememberMe, setRememberMe] = React.useState(false);
  const [modalState, setModalState] = React.useState(false);

  const signInHandler = (event?: React.FormEvent<HTMLFormElement>) => {
    event?.preventDefault();
    signIn({ username: email, password, rememberMe });
  };

  React.useEffect(() => {
    if (isFetching == true) {
      setErrorText(undefined);
      return;
    }

    if (error) {
      switch ((error as FetchBaseQueryError).status) {
        case 410:
          setErrorText(String(lang.get(userLang)?.userDeleted));
          break;
        case 403:
          setModalState(true);
          break;
        case 401:
          setErrorText(String(lang.get(userLang)?.wrongEmailOrPassword));
          break;
        default:
          setErrorText(makeErrorText(error, userLang));
          break;
      }
    } else {
      if (data) {
        dispatch(setProfile(data));
        router.push(ROUTES.panel.home);
      }
    }
  }, [data, error, isFetching, dispatch, router, userLang]);

  return (
    <React.Fragment>
      <FormBoxStyled onSubmit={signInHandler}>
        {errorText && <AuthAlert severity="error" text={errorText} />}
        <TextFieldStyled
          required
          name="email"
          type="email"
          label={lang.get(userLang)?.email}
          value={email}
          onChange={event => setEmail(event.currentTarget.value)}
          autoFocus
        />
        <TextFieldStyled
          required
          type="password"
          name="password"
          label={lang.get(userLang)?.password}
          value={password}
          onChange={event => setPassword(event.currentTarget.value)}
        />
        <FormCheckbox
          label={lang.get(userLang)?.rememberMe}
          name="remember"
          value="remember"
          checked={rememberMe}
          onChange={event => setRememberMe(event.currentTarget.checked)}
        />
        <AuthButtonStyled disabled={isFetching || Boolean(data)}>
          {isFetching ? lang.get(userLang)?.loading : lang.get(userLang)?.signIn}
        </AuthButtonStyled>
        <AuthLinkStyled href={ROUTES.auth.signUp}>
          {lang.get(userLang)?.signUpText}
        </AuthLinkStyled>
        <AuthLinkStyled href={ROUTES.auth.forget}>
          {lang.get(userLang)?.forgotPasswordText}
        </AuthLinkStyled>
      </FormBoxStyled>
      <CustomModal
        open={modalState}
        onClose={() => setModalState(false)}
        title={lang.get(userLang)?.verification}
      >
        <VerifyUser
          email={originalArgs?.username || ''}
          callback={() => setModalState(false)}
        />
      </CustomModal>
    </React.Fragment>
  );
};
export default Authorization;

// nuxt/components/Forms/Auth/Authorization.vue
<script setup lang="ts">
import FormBox from '../FormBox.vue'
import FormAlert from '../FormAlert.vue'
import FormTextInput from '../FormTextInput.vue'
import FormPasswordInput from '../FormPasswordInput.vue'
import FormCheckbox from '../FormCheckbox.vue'
import FormButton from '../FormButton.vue'
import FormAuthLink from '../FormAuthLink.vue'
import CustomModal from '~/components/Other/CustomModal.vue'
import VerifyUser from '~/components/Forms/Auth/VerifyUser.vue'
import { useProfileStore } from '~/stores/profile'
import { makeErrorText } from '~/libs/functions'
import { ROUTES } from '~/libs/constants'

const { t } = useI18n()
const router = useRouter()
const email = ref('')
const emailIsValid = (value: string) => value.length > 0
const password = ref('')
const passwordIsValid = (value: string) => value.length > 0
const rememberMe = ref(false)
const profileStore = useProfileStore()
const errorMsg = ref<string | null>(null)
const verifyModal = ref(false)

function submitHandler() {
  if (emailIsValid(email.value) && passwordIsValid(password.value))
    profileStore.signIn({ username: email.value, password: password.value, rememberMe: rememberMe.value })
}

watch(
  () => profileStore.signInError,
  () => {
    switch (profileStore.signInError?.status) {
      case 410:
        errorMsg.value = t('userDeleted')
        break
      case 403:
        errorMsg.value = null
        verifyModal.value = true
        break
      case 401:
        errorMsg.value = t('wrongEmailOrPassword')
        break
      case undefined:
        errorMsg.value = null
        break
      default:
        errorMsg.value = makeErrorText(profileStore.signInError?.message)
    }
  },
)

watch(
  () => profileStore.profile,
  () => {
    if (profileStore.profile)
      router.push(ROUTES.panel.home)
  },
)
</script>

<template>
  <FormBox @submit="submitHandler">
    <FormAlert v-if="errorMsg" :title="$t('error')" :text="errorMsg" type="error" />
    <FormTextInput
      v-model:model-value="email" required name="email" :label="$t('email')"
      :rules="[emailIsValid]"
    />
    <FormPasswordInput
      v-model:model-value="password" required name="password" :label="$t('password')"
      :rules="[passwordIsValid]"
    />
    <FormCheckbox v-model:model-value="rememberMe" name="rememberMe" :label="$t('rememberMe')" />
    <FormButton block type="submit" color="info" :loading="profileStore.signInPending">
      {{ $t('signIn') }}
    </FormButton>
    <FormAuthLink :href="ROUTES.auth.signUp" :text="$t('signUpText')" />
    <FormAuthLink :href="ROUTES.auth.forget" :text="$t('forgotPasswordText')" />
  </FormBox>
  <CustomModal v-model="verifyModal" :title="$t('verification')">
    <VerifyUser :email="email" @close="verifyModal = false" />
  </CustomModal>
</template>
