// nuxt/components/entities/Forms/Resource/UpdateResource.vue
<script setup lang="ts">
import Form from '~/components/kit/Form/Form.vue'
import FormField from '~/components/kit/Form/FormField.vue'
import FormCheckbox from '~/components/kit/Form/FormCheckbox.vue'
import FormButton from '~/components/kit/Form/FormButton.vue'
import { useResourcesStore } from '~/stores/resources/resources'
import { useMainStore } from '~/stores/main/main'
import type { IResource } from '~/stores/resources/types'

const { resource } = defineProps<{ resource: IResource }>()

const { t, locale } = useI18n()
const resourcesStore = useResourcesStore()
const name = ref(resource.name)
const nameIsValid = (value: string) => value.length > 0
const path = ref(resource.path)
const pathIsValid = (value: string) => value.length > 0
const description = ref(resource.description)
const enabled = ref(resource.enabled)
const mainStore = useMainStore()
const router = useRouter()
const rights = useRights(ROUTES.api.resources)

function submitHandler() {
  if (nameIsValid(name.value) && pathIsValid(path.value)) {
    resourcesStore.update({
      id: resource.id,
      fields: { name: name.value, path: path.value, description: description.value, enabled: enabled.value },
    })
  }
}

watch(
  () => resourcesStore.updatePending,
  () => {
    if (resourcesStore.updatePending === true)
      return
    if (resourcesStore.updateError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(resourcesStore.updateError, locale.value) })
    if (resourcesStore.updateData)
      mainStore.addAlert({ type: 'success', text: t('success') })
  },
)

watch(
  () => resourcesStore.deletePending,
  () => {
    if (resourcesStore.deletePending === true)
      return
    if (resourcesStore.deleteError)
      mainStore.addAlert({ type: 'error', text: makeErrorText(resourcesStore.deleteError, locale.value) })
    if (resourcesStore.deleteData) {
      mainStore.addAlert({ type: 'success', text: t('success') })
      router.push(ROUTES.panel.resources)
    }
  },
)
</script>

<template>
  <Form @submit="submitHandler">
    <FormField v-model:model-value="name" required name="name" :label="$t('name')" :rules="[nameIsValid]" />
    <FormField v-model:model-value="path" required name="path" :label="$t('path')" :rules="[pathIsValid]" />
    <FormField v-model:model-value="description" name="description" :label="$t('description')" />
    <FormCheckbox v-model:model-value="enabled" name="enabled" :label="$t('enabled')" />
    <FormButton
type="submit" color="success" prepand-icon="mdi-content-save" :loading="resourcesStore.updatePending"
      :disabled="!rights.updating || resourcesStore.readData?.default">
      {{ $t('update') }}
    </FormButton>
    <FormButton
type="button" color="error" prepand-icon="mdi-delete" :loading="resourcesStore.deletePending"
      :disabled="!rights.deleting || resourcesStore.readData?.default" @click="resourcesStore.delete(resource.id)">
      {{ $t('delete') }}
    </FormButton>
  </Form>
</template>

// next/components/Forms/Resource/UpdateResource.tsx
import React from 'react';
import { useRouter } from 'next/router';

import resourcesApi from '../../../store/api/resourcesApi';
import { getUpdatedValues, makeErrorText } from '../../../lib/functions';
import { IResource } from '../../../lib/types';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { addAlert } from '../../../store/slices/appSlice';
import FormActions from '../FormActions';
import TextFieldStyled from '../../Other/TextFieldStyled';
import FormBoxStyled from '../FormBoxStyled';
import { ROUTES } from '../../../lib/constants';
import FormCheckbox from '../FormCheckbox';
import useRights from '../../../hooks/useRights';
import dictionary from '../../../locales/dictionary';
import useLang from '../../../hooks/useLang';

const UpdateResource: React.FC<{
  data: IResource;
}> = ({ data }) => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const lang = useLang();
  const t = useAppSelector(store => store.app.t);
  const [update, updateReq] = resourcesApi.useUpdateMutation();
  const [destroy, deleteReq] = resourcesApi.useDeleteMutation();
  const [name, setName] = React.useState(data.name);
  const [path, setPath] = React.useState(data.path);
  const [description, setDescription] = React.useState(data.description || '');
  const [enabled, setEnabled] = React.useState(Boolean(data.enabled));
  const rights = useRights(ROUTES.api.resources);

  const updateHandler = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const updatedValues = getUpdatedValues<IResource>(
      data,
      { name, path, description: description || null },
    );
    if (Object.keys(updatedValues).length == 0) {
      dispatch(addAlert({ type: 'warning', text: t.nothingToUpdate }));
    } else {
      update({ id: data.id, fields: updatedValues });
    }
  };

  React.useEffect(() => {
    if (updateReq.isLoading) {
      return;
    }
    if (updateReq.data === false || updateReq.error) {
      dispatch(addAlert({ type: 'error', text: makeErrorText(updateReq.error, lang.current) }));
    }
    if (updateReq.data) {
      dispatch(addAlert({ type: 'success', text: dictionary[lang.current].success }));
    }
  }, [updateReq.data, updateReq.error, updateReq.isLoading, dispatch]);

  React.useEffect(() => {
    if (deleteReq.isLoading) {
      return;
    }
    if (deleteReq.data === false || deleteReq.error) {
      dispatch(addAlert({ type: 'error', text: makeErrorText(deleteReq.error, lang.current) }));
    }
    if (deleteReq.data) {
      dispatch(addAlert({ type: 'success', text: dictionary[lang.current].success }));
      router.push(ROUTES.panel.users);
    }
  }, [deleteReq.data, deleteReq.error, deleteReq.isLoading, dispatch, router]);

  return (
    <FormBoxStyled onSubmit={updateHandler}>
      <TextFieldStyled
        required
        name="name"
        type="text"
        label={t.name}
        value={name}
        onChange={event => setName(event.currentTarget.value)}
        disabled={data?.default}
      />
      <TextFieldStyled
        required
        name="path"
        type="text"
        label={t.path}
        value={path}
        onChange={event => setPath(event.currentTarget.value)}
        disabled={data?.default}
      />
      <TextFieldStyled
        name="description"
        type="text"
        label={t.description}
        value={description}
        onChange={event => setDescription(event.currentTarget.value)}
        disabled={data?.default}
      />
      <FormCheckbox
        label={t.enabled}
        name="enabled"
        value="enabled"
        checked={enabled}
        onChange={() => setEnabled(!enabled)}
      />
      {data && !data.default && (
        <FormActions
          update={{
            loading: updateReq.isLoading,
            disabled: !rights.updating,
          }}
          destroy={{
            action: () => destroy(data.id),
            loading: deleteReq.isLoading,
            disabled: !rights.deleting,
          }}
        />
      )}
    </FormBoxStyled>
  );
};
export default UpdateResource;
