// nuxt/pages/resources/index.vue
<script setup lang="ts">
definePageMeta({
  middleware: ['auth'],
  layout: 'panel',
  name: 'resources',
  title: 'resources',
  description: 'resources',
})

const router = useRouter()
const route = useRoute()
const page = ref(Number(route.query.page) || 1)
const quantity = ref(Number(route.query.quantity) || 25)
const { data, execute } = resourcesApi.getList(ROUTES.api.resources)
if (import.meta.server)
  await execute({ reqPage: page.value, reqLimit: quantity.value, reqCount: true })

watch(
  page,
  () => {
    router.push({ query: { ...route.query, page: page.value } })
  },
)

watch(
  quantity,
  () => {
    router.push({ query: { ...route.query, quantity: quantity.value } })
  },
)
</script>

<template>
  <ResourcesList
    v-model:page="page"
    v-model:quantity="quantity"
    :count="data?.count"
    :rows="data?.rows"
  />
</template>

// next/src/app/(panel)/resources/page.tsx
import { FC } from 'react';
import { Metadata } from 'next/types';

import resourcesService from '@/shared/api/resources/resourcesService';
import { IAppPage } from '@/app/types';
import ResourcesPage from '@/views/Panel/Resources/ResourcesPage';
import { getT } from '@ap/shared';

export const generateMetadata = async (): Promise<Metadata> => {
  const t = getT();
  return {
    title: t.resources,
    description: t.resources,
  };
};

const Page: FC<IAppPage> = async (props) => {
  const t = getT();
  const page = Number(props.searchParams.page) || 1;
  const quantity = Number(props.searchParams.quantity) || 25;
  const { data } = await resourcesService.getList({
    reqPage: page,
    reqLimit: quantity,
    reqCount: true,
  });

  return <ResourcesPage data={data} h1={t.resources} />;
};
export default Page;
