// nuxt/pages/forgot-password.vue
<script setup lang="ts">
import ForgotPassword from '~/components/Forms/Auth/ForgotPassword.vue'

definePageMeta({
  middleware: ['auth'],
  layout: 'authorization',
  name: 'forgotPassword',
  title: 'forgotPassword',
  description: 'forgotPassword',
})
</script>

<template>
  <ForgotPassword />
</template>

// next/src/app/(auth)/forgot-password/page.tsx
import { Metadata } from 'next/types';
import { FC } from 'react';

import getT from '@/hooks/getT';
import ForgotPasswordPage from '@/components/Pages/Auth/ForgotPasswordPage';

export const generateMetadata = async (): Promise<Metadata> => {
  const t = await getT();
  return {
    title: t.forgotPassword,
    description: t.forgotPassword,
  };
};

const ForgotPassword: FC = async () => {
  const t = await getT();
  return <ForgotPasswordPage h1={t.forgotPassword} />;
};
export default ForgotPassword;
