// nuxt/components/Layout/SideBarMenuItem.vue
<script setup lang="ts">
import type { ISideBarMenuItem } from '~/libs/types'

const props = defineProps<ISideBarMenuItem>()
const route = useRoute()
const router = useRouter()
const selected = ref(false)

watch(
  () => route.path,
  () => {
    let result = Boolean(props.href)
    const pathArr = route.path.split('/')
    const linkArr = props.href ? props.href.split('/') : []
    linkArr.forEach((value, index) => {
      if (value !== pathArr[index])
        result = false
    })
    selected.value = result
  },
  { immediate: true },
)
</script>

<template>
  <v-list-group v-if="childs" :value="`${title}: ${href}`" :fluid="true">
    <template #activator="{ props: itemProps }">
      <v-list-item v-bind="itemProps" :prepend-icon="icon" :title="title" />
    </template>
    <SideBarMenuItem v-for="child in childs" :key="child.title" v-bind="child" />
    <v-divider />
  </v-list-group>
  <v-list-item
    v-else :prepend-icon="icon" :title="title" link :href="href" :active="selected"
    @click.prevent="router.push(href || '#')"
  />
</template>

// apps/frontend/panel-react/src/widgets/SideBar/SideBarMenuItem.tsx
import { FC, MouseEventHandler, ReactNode, useMemo, useState } from 'react';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Divider from '@mui/material/Divider';
import Collapse from '@mui/material/Collapse';
import ExpandMore from '@mui/icons-material/ExpandMore';
import ExpandLess from '@mui/icons-material/ExpandLess';
import { usePathname, useRouter } from 'next/navigation';

import { IMenuItem } from '@ap/shared/src/types';
import { checkActiveLink } from '@ap/shared/src/libs';

const SideBarMenuItem: FC<IMenuItem<ReactNode>> = ({
  href,
  title,
  icon,
  childs,
}) => {
  const router = useRouter();
  const pathname = usePathname();
  const [open, setOpen] = useState(() =>
    checkActiveLink(pathname, { href, childs })
  );

  const linkHandler: MouseEventHandler<HTMLDivElement> = (event) => {
    event.preventDefault();

    if (href) {
      router.push(href);
    }

    if (childs) {
      setOpen(!open);
    }
  };

  const selected = useMemo(() => {
    let result = Boolean(href);
    const pathArr = pathname.split('/');
    const linkArr = href?.split('/') || [];

    linkArr.forEach((value, index) => {
      if (value != pathArr[index]) {
        result = false;
      }
    });

    return result;
  }, [pathname, href]);

  return (
    <>
      <ListItem disablePadding>
        <ListItemButton
          {...(href && { href })}
          selected={selected}
          onClick={linkHandler}
        >
          {icon && <ListItemIcon>{icon}</ListItemIcon>}
          <ListItemText primary={title} />
          {childs && (open ? <ExpandLess /> : <ExpandMore />)}
        </ListItemButton>
      </ListItem>
      {childs && (
        <Collapse in={open} timeout="auto">
          <Divider />
          {childs.map((item, index) => (
            <SideBarMenuItem
              key={`sbmi:${index}:${item.title}:${item.href}`}
              {...item}
            />
          ))}
        </Collapse>
      )}
    </>
  );
};
export default SideBarMenuItem;
